omisego/ewallet

- README.md
Little markdown fail made while writing the Readme... This PR brings the `current` to a new line and adds the missing `__` before the disclaimer.
> Fix format for stable/current explanation in Readme

- apps/ewallet/priv/repo/report_minimum.exs
Issue/Task Number: T828
This PR fixes the typo that would make the Authorization header in the seed message won't work.
- Changed the incorrect `OMGServer` auth scheme to `OMGAdmin` (the former is for eWallet API, the latter is for Admin API).
Textual change.
The change will be reflected when running `mix seed`.
Usual deployment. No extra steps required.
> Fix seed message typo on Authorization header's scheme

- README.md
This PR fixes the URL used for cloning in the Getting Started section of the readme.
> Use https:// instead git@ for cloning

- apps/admin_api/lib/admin_api/v1/serializers/transaction_serializer.ex
- apps/admin_api/priv/swagger.yaml
- apps/admin_api/test/admin_api/v1/serializers/transaction_serializer_test.exs
- apps/admin_api/test/admin_api/v1/views/transaction_view_test.exs
- apps/ewallet_api/lib/ewallet_api/v1/serializers/json/transaction_serializer.ex
- apps/ewallet_api/priv/swagger.yaml
- apps/ewallet_api/test/ewallet_api/v1/serializers/json/transaction_serializer_test.exs
- apps/ewallet_api/test/ewallet_api/v1/views/transaction_view_test.exs
Issue/Task Number: T50 - [Issue](https://github.com/omisego/ruby-sdk/issues/11)
The transactions sent back in the listing endpoints don't currently contain the `metadata` field. This PR fixes that.
- Add `metadata` to EWallet `TransactionSerializer`
- Add `metadata` to AdminAPI `TransactionSerializer`
- Fixes tests
Nothing much, except a new field in the serializers.
.
No special requirements.
> Add metadata to transactions list

- apps/admin_api/priv/swagger.yaml
- apps/ewallet_api/priv/swagger.yaml
Thanks to a great suggestion by kartsims in #93, this PR replaces `search_term` and `search_terms` value in swagger doc to empty strings and objects so that requests from Swagger UI show unfiltered results by default.
- Updated swagger docs for both eWallet API and Admin API
Textual update
Try making `*.all` requests from Swagger UI. Instead of showing empty results with the default request bodies, they should now return unfiltered results.
Usual deployment. No extra steps required.
> Default search_term in swagger docs to empty strings

- apps/ewallet/config/config.exs
- apps/ewallet/lib/ewallet/web/paginator.ex
- apps/ewallet/test/ewallet/web/paginator_test.exs
- docs/setup/env.md
Thanks to a great suggestion by kartsims in #93, this PR adds a maximum limit to `per_page` input to prevent a request overloading the system by sending a very high `per_page` value.
- Updated `EWallet.Web.Paginator` to support `max_per_page`
- Added a configurable value in `ewallet/config/config.exs` called `max_per_page`
- Set the default `max_per_page` to 100
- Updated `docs/setup/env.md` to include `REQUEST_MAX_PER_PAGE`
- If the given `per_page` is higher than the `max_per_page`, the `per_page` will automatically be set to the `max_per_page` value instead of returning an error.
Try send a request with a very high `per_page` value, you should see the response returning only up to the defined `max_per_page`.
You should also see that the response's …
> Add maximum `per_page` value

- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
- apps/local_ledger/lib/local_ledger/entry.ex
- apps/local_ledger/lib/local_ledger/entry/validator.ex
- apps/local_ledger/lib/local_ledger/errors/same_address_error.ex
- apps/local_ledger/test/local_ledger/entry_test.exs
Issue/Task Number: T65
Currently, it is possible to create transactions between the same two addresses. This PR adds a mechanism preventing that.
- Raise a `SameAddressError` error if the same address is found in both the debits and credits.
1. Extract the addresses for debits and credits.
2. Do an intersect and check if anything common was found.
3. Raise the `SameAddressError` if that's the case, else let the flow continue. 
-
-
> T65 - Prevent transactions between identical addresses

- .gitignore
- apps/url_dispatcher/lib/url_dispatcher/plug.ex
- apps/url_dispatcher/test/test_helper.exs
- apps/url_dispatcher/test/url_dispatcher/plug_test.exs
- public/uploads/test.txt
Issue/Task Number: T37, T38
This PR removes the non-trailing slash redirect and add simple tests to make sure the urls are being forwarded correctly.
- Remove redirects for urls without trailing slashes
- Added basic http status tests for all the url prefixes handled by `UrlDispatcher`
I simply removed handling of the non-trailing slash version of the urls and removed trailing slashes from the actual dispatchers. Since Phoenix's router is agnostic about trailing slashes, both urls with and without trailing slashes are still served.
The good part is that curl will now work with or without trialing slashes without having to add `curl -L ...`
Try call urls such as `/api`, `/admin`, `/admin/api` via curl. They will no longer require `-L` flag to redirect.
N/A
> Remove UrlDispatcher redirects and add unit tests

- apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/admin_api/test/admin_api/v1/controllers/account_membership_controller_test.exs
Issue/Task Number: T44
This PR fixes 500 error when `/admin/api/account.assign_user` is requested with an invalid email format.
- Changed all error returns from an atom to `{:error, _}` for consistency in handling them
- Added a test that submits /admin/api/account.assign_user with an invalid email format
Instead of adding another `else` condition, I refactored so that the `else` cases should always return `{:error, _}`. This makes some statements a little more wordy but overall producing less conditions in the logic, which should be better.
Try make an authenticated call to /admin/api/account.assign_user with an invalid email (e.g. an email without @ sign). The response should return `success: false` with the error code `user:invalid_email`.
Usual deployment. No extra steps.
> Fix 500 error when assigning a user with invalid email format

- apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_controller_test.exs
- apps/ewallet/priv/repo/report_minimum.exs
- apps/ewallet/priv/repo/report_sample.exs
- apps/ewallet_db/config/config.exs
- apps/ewallet_db/config/dev.exs
- apps/ewallet_db/config/test.exs
Issue/Task Number: T93
This PR fixes #98. The seeder will fallback to "https://example.com" if `base_url` is not set, which can be usual for a system that's being setup for the first time.
- Moved `:base_url` config assignment to `apps/ewallet_db/config/config.exs`
- Specifically prevent `:base_url` in `apps/ewallet_db/config/prod.exs` from having a default value
- Added fallback value for `:base_url` in seeder output
By doing the changes above, we guarantee that `:prod` environment will never accidentally set to a default value, while still allowing seeders to output a readable result.
Run `mix seed` and `mix seed --sample` on `:prod` should produce urls with `https://example.com` as their base.
Usual deployment. No extra steps.
> Seeder fallbacks to example.com if base_url is not set

- apps/ewallet_api/priv/spec.yaml
Issue/Task Number: T133
Add base responses to the API spec for transaction request/request consumption endpoints
- Wrap base responses to the following endpoints
- `/me.create_transaction_request`
- `/me.get_transaction_request`
- `/me.consume_transaction_request`
Textual changes
Navigate to https://ewallet.staging.omisego.io/api/docs and see the example responses for the 3 TransactionRequest endpoints.
N/A
> Fix TransactionRequest-related API spec missing base responses

- apps/ewallet/priv/repo/seeder.exs
- apps/ewallet/priv/repo/seeders/initial_user.exs
Issue/Task Number: T121
The seed is hardcoded to use `admin_master@example.com` which is not very useful for other than a demo setup. This PR makes that first admin's email address customizable during the start of `mix seed`.
- Changed the seed to ask for email address input at the beginning of the seed.
I decided to use `Application.put_env/3` to persist the email address value across the seed scripts. This is probably not the best approach but it works and is quick to implement. Definitely don't want this to stick around after we do a refactor of the seed.
Run `mix seed` you should see the prompt after:
```
$ mix seed
What email address should we set for your first admin user?
This email is required for logging into the admin panel.
If a user with this email already exists, it will …
```
> Customizable admin email in the seed

- apps/ewallet/priv/repo/report_minimum.exs
- apps/ewallet/priv/repo/report_sample.exs
The seeder's output still refers to `*/swagger` instead of `*/docs`.
- Replace `*/swagger` with `*/docs`
N/A
Running `mix seed` and `mix seed --sample` should return urls with `*/docs` instead of `*/swagger`.
Usual deployment.
> Fix docs urls in the seeder

- apps/admin_panel/assets/src/omisego/config.js
- apps/admin_panel/config/config.exs
- apps/admin_panel/lib/admin_panel/controllers/page_controller.ex
- apps/admin_panel/mix.exs
- apps/admin_panel/test/admin_panel/controllers/page_controller_test.exs
- apps/admin_panel/test/admin_panel/test_assets/dist/index.html
- apps/admin_panel/test/test_helper.exs
- apps/ewallet/priv/repo/report_minimum.exs
Issue/Task Number: T136
This PR adds a fallback message in case the front-end assets have not been built, improves the tests so that they reliably tests cases both when assets can be found and when they're not found, and auto-injects the API key pair from the backend to the admin panel.
- Added `:dist_path` config to specify where to find the compiled frontend assets
- Add a fallback so that the admin panel serves a descriptive message if it cannot serve the assets.
- Update tests so they reliably tests both when the assets can be found and when they can't.
- Automatically injects API key ID and API key into the frontend app.
- `:dist_path` config is added so `AdminPanel.PageController` does not rely on a hardcoded path. This is useful for changing the path to the test assets when …
> Serve fallback message when assets are missing & API key injection

- apps/admin_panel/assets/src/components/Alerter.jsx
- apps/admin_panel/assets/src/pages/public/PublicLayout.jsx
- apps/admin_panel/assets/src/styles/components/_alert.scss
Issue/Task Number: `154-fix-alert-overlap-the-logo`
The alert box on the login page doesn't look nice because it overlaps the logo. This PR will solve it.
- A better alert box
**From**
**To**
- Add `display: inline-block` to `.alert` class
- Create class `.alert-center`
- Apply `.alert-center` to the root of the `Alerter` component
`N/A`
`N/A`
> Fix alert box overlap the logo on the login page

- apps/admin_panel/config/config.exs
Issue/Task Number: T153
Adds `ecto_repos: []` to the admin panel's config.exs
- Add `ecto_repos: []` to `apps/admin_panel/config/config.exs`
With #120, admin_panel app now requires a database connection. Ecto requires an empty `:ecto_repos` config even that the database connection is handled by `EWalletDB.Repo`.
Run `mix ecto.migrate` should not cause the following warning:
```
==> admin_panel
warning: could not find repositories for application :admin_panel.
You can avoid this warning by passing the -r flag or by setting the
repositories managed by this application in your config/config.exs:
config :admin_panel, ecto_repos: [...]
The configuration may be an empty list if it does not define any repo.
```
N/A
> Fix ecto warning when running migrations

- apps/admin_api/test/admin_api/v1/controllers/self_controller_test.exs
- apps/ewallet/lib/ewallet/helper.ex
- apps/ewallet/test/ewallet/helper_test.exs
Issue/Task Number: T158
Tests are randomly failing due to list assertions on returns that are not always sorted in the same order.
- Added `EWallet.Helper.members?/2`
- Changed `AdminAPI.V1.SelfControllerTest` to use `EWallet.Helper.members?/2` instead of direct comparison of the lists.
We could easily fix this by adding an `order_by` to the query but this changes the nature of the query so it's not desirable. This fix instead creates a function `EWallet.Helper.members?/2` that checks if an enumerable is a subset of another regardless of the list order. It is less efficient than sorting the query, but in return it gives us tests with no extra side effects.
Run `mix test` especially during CI process. Test failures from incorrect ordering should disappear.
N/A
> Fix tests randomly failing due to DB return sequence

- apps/admin_api/priv/spec.yaml
- apps/ewallet_db/lib/ewallet_db/account.ex
- apps/ewallet_db/lib/ewallet_db/account_validator.ex
- apps/ewallet_db/test/ewallet_db/account_test.exs
- apps/ewallet_db/test/ewallet_db/account_validator_test.exs
Issue/Task Number: T157
To prevent unnecessary complexity without observing real-life use cases first, we have decided to limit the number of account levels to 1 (one master account with uncapped direct children).
- Add a new function `Account.get_depth/1` that returns the depth of the given account relative to the master account.
- Add new validator `AccountValidator.validate_account_level/2` that checks that the inserting/updating account does not go beyond the given max account level.
- Add this new validator above to the Account's changeset.
N/A
Call `/admin/api/account.create` or `/admin/api/account.update` and try to set the account's parent to a parent that already reached the maximum account level (i.e. you should not be able to create an account that does not have the master …
> Implement account level limit

- Jenkinsfile
Fix staging deploy failure. This is due to `s6-setuidgid` will only set the UID/GID and leave updating user env to the user. When mix tried to look for the `.erlang` during migration, it will look at `$HOME` (`/root`) which failed due to lack of permissions. This fix simply add `s6-env HOME=/tmp/ewallet` to the migration command (as well as explicitly calling `execlineb`).
> Set HOME after dropping privileges before running migration

- apps/ewallet/lib/ewallet/web/paginator.ex
- apps/ewallet/test/ewallet/web/paginator_test.exs
Issue/Task Number: T174 - [Issue](https://github.com/omisego/ruby-sdk/issues/13)
This PR allows the pagination params to be sent as string (still need to be valid integers inside though).
- Handle integer sent as string for pagination.
Added two new functions that check if the params are not integers and try to convert them in base 10.
No change, just more flexibility.
Nope.
> Allow pagination params to be sent as string

- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
- apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
- apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
- apps/local_ledger_db/lib/local_ledger_db/errors/insufficient_funds_error.ex
Issue/Task Number: T9
This PR uses the `subunit_to_unit` from minted token to present more readable errors when funds are not sufficient for a transaction.
- Move error message to eWalletAPI / AdminAPI for insufficient funds
- Format amounts as floats
- Update tests
In order to show the actual amount, we need the minted token which cannot be retrieved in the local ledger, therefore it was moved in the API. 
The code is duplicated in the error handlers, but the refactoring of the error handling is coming soon and will unify those.
> Improve insufficient funds error

- apps/ewallet_api/config/prod.exs
Issue/Task Number: T181
Currently getting the following error when trying to use the websockets in staging:
```
03:04:00.062 [error] Could not check origin for Phoenix.Socket transport.
This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:
1. update [url: [host: ...]] to your actual host in the
config file for your current environment (recommended)
2. pass the :check_origin option when configuring your
endpoint or when configuring the transport in your
UserSocket module, explicitly outlining which origins
are allowed:
check_origin: ["https://example.com", …
```
> Disable check_origin for web socket Endpoint

- docs/setup/env.md
Issue/Task Number: T177
This PR adds to the env documentation that the sender email address can be configured via `SENDER_EMAIL` environment variable.
- Add `SENDER_EMAIL` to `docs/env.md`
N/A
N/A
N/A
> Add SENDER_EMAIL to env docs

- apps/ewallet/priv/repo/seeders/account.exs
Issue/Task Number: T187
When running `mix seed`, inserting of "branch1" and "branch2" accounts fail due to it's still being configured under "branch1" and "branch2" which is no longer valid after #126.
- Changed parent of "brand1" and "brand2" seed accounts to "master_account"
N/A
Run `mix seed` should no longer throw error on creating accounts.
N/A
> Fix ewallet seed error trying to insert multiple-level accounts

- README.md
Fixes a typo on docker instructions in the README. Thanks to "fumi" from Rocket Chat channel for spotting this issue.
N/A
N/A
N/A
N/A
> Fix docker setup instructions

- Dockerfile
- Jenkinsfile
We now use custom base image at [omisegoimages](https://hub.docker.com/r/omisegoimages) to speed up builds and to allow for more stable base.
> Switch to use omisegoimages/ewallet-base to build Docker

- apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
Issue/Task Number: T200
The `parent_id` should not be mandatory to create account.
- Remove `parent_id` as mandatory from account creation in Admin API.
> Remove parent_id as mandatory for account creation

- apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
- apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Issue/Task Number: T198
@mederic-p requested a way to see how many consumptions had been made for a request. This PR fixes that.
- Add `current_consumptions_count`
> Add transaction consumption current count

- apps/admin_api/lib/admin_api/v1/controllers/minted_token_controller.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
- apps/ewallet/lib/ewallet/gates/mint_gate.ex
- apps/ewallet_db/lib/ewallet_db/mint.ex
Issue/Task Number: T192
The possibility to mint tokens (add more in circulation) was missing from the Admin API. This PR fixes that.
- Add a new endpoint: `minted_token.mint`
- Add tests
- Update swagger docs
Not much to describe here, just a new endpoint using the existing minting mechanism.
Give it an ID and an amount and you should be able to mint.
> Add minting token endpoints

- Dockerfile
Fix a build process where mix deps and compilation are being done twice, once with `ewallet` user and again with `root` user.
> Fix build where mix dependencies are being resolved twice

- apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
Issue/Task Number: T169
Fix more random test failures including #147.
Instead of comparing with a fixed list, tests are updated to use `Enum.all?/2` with `Enum.any?/2` instead.
N/A
N/A
N/A
> Fix more random test failures

- apps/admin_api/config/config.exs
- apps/admin_api/config/test.exs
- apps/admin_api/lib/admin_api/v1/plugs/client_auth_plug.ex
- apps/admin_api/lib/admin_api/v1/plugs/user_auth_plug.ex
- apps/admin_api/test/admin_api/v1/plugs/client_auth_plug_test.exs
- apps/admin_api/test/admin_api/v1/plugs/user_auth_plug_test.exs
Issue/Task Number: T179
This PR makes the admin API Keys optional (disabled by default).
- Add a new ENV variable: `ENABLE_ADMIN_CLIENT_AUTH`, `"false"` by default.
- It stays enabled for the tests, but some tests were added to test it.
> Make Admin API Keys optional

- apps/ewallet_db/config/dev.exs
- apps/ewallet_db/config/prod.exs
- apps/local_ledger/config/dev.exs
- apps/local_ledger/config/prod.exs
Issue/Task Number: T216
Quantum has an option to work within a cluster and avoid duplicated jobs. This PR enables it.
- Enable `global` mode for Quantum
> Run Quantum in global mode

- apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
- apps/ewallet/lib/ewallet/web/search_parser.ex
- apps/ewallet/test/ewallet/web/search_parser_test.exs
Issue/Task Number: T10
This PR adds field mapping to `SearchParser`
- Updated `SearchParser.to_query/3` to support mapping of requested fields into actual fields in the database.
Simply added a new function clause that takes in a map which is used to determine what fields are to be mapped.
Calling endpoints that allow `search_terms` should now allow mapped fields e.g. `created_at` to be mapped and searched in the database field `inserted_at`.
Usual deployment.
> SearchParser supports mapped fields

- apps/ewallet/lib/mix/tasks/omg.deps.ex
Issue/Task Number: T122
This PR adds the ability to run a single command, `mix omg.deps`, to fetch back-end and front-end dependencies in one go.
- Add new `mix omg.deps` task
The actual command for the Elixir's mix task is `mix deps.get` but I decided to not include `.get` for easier typing and should align better with the muscle memory we have for `mix omg.server`.
Run `mix omg.deps` on the app's root directory.
Usual deployment
> Add `mix omg.deps` to get fullstack deps

- apps/admin_api/test/admin_api/v1/views/transaction_view_test.exs
- apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
- apps/ewallet/test/ewallet/web/v1/serializers/transaction_serializer_test.exs
- apps/ewallet_api/test/ewallet_api/v1/views/transaction_view_test.exs
Issue/Task Number: T247
Minted tokens in the transaction serializer was sometimes `nil` because no preloaded. This PR fixes that and adds the `minted_token_id` to be consistent with the new approach to serializer (`id` + `object` if preloaded).
- Update the `TransactionSerializer` module
- Fix the tests
How can this change be deployed? Any special requirement?
> Preload minted token in transactions

- apps/ewallet/lib/ewallet/web/preloader.ex
- apps/ewallet/priv/repo/seeders/account.exs
- apps/ewallet/priv/repo/seeders/api_key.exs
- apps/ewallet/priv/repo/seeders/initial_api_key.exs
- apps/ewallet/priv/repo/seeders/minted_token.exs
Issue/Task Number: T218
Following #149, @jarindr found out that `mix seed` fails due to id/uuid references. This PR updates all seed scripts to correctly use `id` vs. `uuid` during the seed.
- Update seed scripts to use `id` when displaying info, and use `uuid` and `relation_uuid` when doing direct inserts to the database.
To follow #149 correctly, the code interacting directly with the schema or the database need to use `uuid` and/or `relation_uuid`. While other code e.g. when displaying inserted data, the `id` should be used.
Run `mix seed` and `mix seed --sample` should be successful.
> Fix seeds failing due to id/uuid misreference

- apps/ewallet_db/priv/repo/migrations/20180424131331_add_symbol_to_minted_token_id.exs
Issue/Task Number: T245
This PR adds the minted token 's symbol to its ID, which was missing in #149's migrations.
- Add a new migration that adds the minted token's symbol to its IDs.
A simple DB migration that checks for `<non_underscores>_<non_underscores>` and add the symbol accordingly. Otherwise no changes is made.
Run `mix ecto.migrate`.
If your minted tokens already have the IDs containing the symbol, you can follow these steps to verify this PR:
1. Run `mix ecto.migrate`. This brings the database to the latest migration.
2. Run `mix ecto.rollback --step 1` This triggers the PR's down() function and minted tokens are reverted back to their IDs without symbols. Verify manually in database that minted token IDs do not contain symbols.
3. Run `mix ecto.migrate` again. This should …
> Add symbol to existing minted token's IDs

- apps/admin_api/lib/admin_api/v1/controllers/auth_controller.ex
- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/lib/admin_api/v1/serializers/auth_token_serializer.ex
- apps/admin_api/lib/admin_api/v1/views/auth_view.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/auth_controller_test.exs
- apps/admin_api/test/admin_api/v1/serializers/auth_token_serializer_test.exs
- apps/admin_api/test/admin_api/v1/views/auth_view_test.exs
- apps/admin_api/test/support/conn_case.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
- apps/ewallet_api/lib/ewallet_api/v1/serializers/auth_token_serializer.ex
- apps/ewallet_api/test/ewallet_api/v1/serializers/auth_token_serializer_test.exs
- apps/ewallet_api/test/ewallet_api/v1/views/auth_view_test.exs
- apps/ewallet_db/lib/ewallet_db/auth_token.ex
- apps/ewallet_db/lib/ewallet_db/user.ex
- apps/ewallet_db/priv/repo/migrations/20180425050633_add_account_uuid_to_auth_token.exs
- apps/ewallet_db/test/ewallet_db/auth_token_test.exs
- apps/ewallet_db/test/support/factory.ex
Issue/Task Number: T248
Based on a request from the Admin Panel implementer @jarindr, we've decided to add the `current_account` in the `AuthToken` returned when logging in. This PR does just that, as well as offering a way to update the current account with `auth_token.switch_account`.
- Add `/auth_token.switch_account`
- Refactor serializers and views to allow the `AuthToken` to contain the whole `user` and `account` objects
> Add account to auth tokens in Admin API

- apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
- apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
- apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
- apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Issue/Task Number: T258
This fixes the issue:
```ex
Request: POST /api/me.consume_transaction_request
** (exit) an exception was raised:
** (KeyError) key :minted_token_id not found in: %EWalletDB.TransactionRequest{<manually_redacted>}
(ewallet) lib/ewallet/gates/transaction_consumption_gate.ex:164: EWallet.TransactionConsumptionGate.validate_minted_token/2
(ewallet) lib/ewallet/gates/transaction_consumption_gate.ex:132: EWallet.TransactionConsumptionGate.do_consume/2
(ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
(db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
(db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
(db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
(ewallet) …
```
> Fix error 500 when consuming request with a different minted token

- apps/ewallet_db/priv/repo/migrations/20180430045654_add_id_prefix_to_account.exs
Issue/Task Number: T262
This PR adds the prefix "acc_" which was missing from existing accounts.
- Add a new migration that adds "acc_" prefix to existing accounts.
This is a simple DB migration that adds the prefix if the existing ID length is 26 (the length of new ULID but without prefix).
Run `mix ecto.migrate`.
You can follow these steps to verify this PR:
1. Run `mix ecto.migrate`. This brings the database to the latest migration.
2. Run `mix ecto.rollback --step 1` This triggers the PR's down() function and accounts are reverted back to their IDs without the prefix. Verify manually in database that account IDs do not contain the prefix.
3. Run `mix ecto.migrate` again. This should trigger this PR's migration script again. Verify manually in database that account IDs now contain the …
> Add missing prefix to account ID

- apps/ewallet_api/priv/spec.yaml
Issue/Task Number: T239
The swagger docs had invalid path names for consumption approval/rejection. This PR fixes that.
> Fix Swagger doc for consumption endpoints

- apps/ewallet/priv/repo/report_minimum.exs
- apps/ewallet/priv/repo/report_sample.exs
- apps/ewallet/priv/repo/seeders/auth_token.exs
Issue/Task Number: T270
Fixes seed error due to the way `AuthToken.generate/2` is returned since #166. Also reported by #173.
- Update seed reports to expect the auth_token as struct, not string
Simple fix of accessing a struct vs. string
Run `mix do reset, mix seed --sample` should output the seed report successfully without any errors.
No extra steps required during deploy.
> Fix seed's argument error

- apps/ewallet/priv/swagger.html
Issue/Task Number: T279
Shows data models at the bottom of the Swagger UI.
- Changed SwaggerUI's `defaultModelsExpandDepth` to 1 
- Changed SwaggerUI's `defaultModelExpandDepth` to 1
- Changed SwaggerUI's `defaultModelsExpandDepth` to 1 so the models are shown
- Changed SwaggerUI's `defaultModelExpandDepth` to 1 so it expands only 1 level and not clutter the screen too much
Try access via browser: `/api/docs` or `/admin/api/docs`
Deploy as usual
> Show data schemas on Swagger UI

- apps/ewallet/config/dev.exs
- apps/ewallet/config/prod.exs
- apps/ewallet/lib/ewallet/application.ex
- apps/ewallet/lib/ewallet/scheduler.ex
- apps/ewallet/lib/ewallet/schedulers/transaction_consumption_scheduler.ex
- apps/ewallet/lib/ewallet/schedulers/transaction_request_scheduler.ex
- apps/ewallet/mix.exs
- apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
- apps/ewallet/test/ewallet/schedulers/transaction_request_scheduler_test.exs
- apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
- apps/ewallet_db/config/dev.exs
- apps/ewallet_db/config/prod.exs
- apps/ewallet_db/lib/ewallet_db/application.ex
- apps/ewallet_db/lib/ewallet_db/scheduler.ex
- apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
- apps/ewallet_db/mix.exs
Issue/Task Number: T264
There is currently no way for a client to know that a consumption has expired. This PR adds the submission of a failed finalized consumption to represent the expiration.
- Move Scheduler from EWalletDB to EWallet in order to be able to trigger events
- Add Scheduler modules that take care of sending events
- Add `returning` when doing the `update_all` call (expiration) to get the list of consumptions that need to be sent as events
> Expired consumption event

- apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
- apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
- apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
- apps/ewallet_api/priv/spec.yaml
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
- apps/ewallet_db/lib/ewallet_db/transaction_request.ex
- apps/ewallet_db/priv/repo/migrations/20180511045020_add_max_consumptions_per_user_to_transaction_requests.exs
Issue/Task Number: T229
This PR adds a way to specify that a transaction request should be consumed a specific amount of time per user (usually 1 in the case of a giveaway).
- Add `max_consumptions_per_user` to transaction requests
- Ensure that value has not been reached by the current user (set on the balance)
- Add tests 
- Update Swagger spec
> Add max_consumption_per_user for transaction requests

- apps/admin_api/lib/admin_api/v1/controllers/minted_token_controller.ex
Issue/Task Number: T271
Fixes `"client:invalid_parameter"` error when trying to create a minted token with `/admin/api/minted_token.create`. Fixes #177.
Depends on #179 otherwise the test with `enable_client_auth: false` is not possible.
- Fix  `/minted_token.create`'s account association to the master account
This bug follows #151 that the client authentication (using API ID and API key) in AdminAPI can now be optional. This means `conn.assigns.account` assigned during `ClientAuthPlug` may not always be available, but `/minted_token.create` still relies on it.
Since we have no use case for minted token in non-master accounts, it's best to fix it to master account until we have a solid reason not to.
Requesting `/minted_token.create` with valid parameters should now be successful.
Deploy …
> Fix minted token's association with master account

- apps/ewallet_db/priv/repo/migrations/20180430105218_update_predictable_minted_token_id.exs
- apps/local_ledger_db/priv/repo/migrations/20180430105449_update_predictable_minted_token_id.exs
Issue/Task Number: T263
Fixes the issue that #149 did not completely convert the minted token IDs in local ledger, therefore the minted token IDs in the local ledger and ewallet are inconsistent even though they represent the same minted token.
- Fixes some errors when running `mix seed --sample`
- Adds a migration that updates the `minted_token.id` in both the local ledger and ewallet to be consistent.
**Cause:** This bug is caused by missing migrations in `local_ledger_db` that should have converted minted token IDs from the previous `SYM:uuid` to `tok_SYM_ulid` format but did not. This causes transactions to fail as it could not retrieve the balance in `local_ledger_db` using the new `tok_SYM_ulid` format.
**Solution:** Since this project is still in beta, it is possible to wipe the …
> Fix inconsistent minted token IDs between local ledger and ewallet

- apps/admin_api/config/test.exs
- apps/admin_api/lib/admin_api/v1/plugs/client_auth_plug.ex
- apps/admin_api/lib/admin_api/v1/plugs/user_auth_plug.ex
- apps/admin_api/test/admin_api/v1/controllers/auth_controller_test.exs
- apps/admin_api/test/admin_api/v1/plugs/client_auth_plug_test.exs
- apps/admin_api/test/admin_api/v1/plugs/user_auth_plug_test.exs
- apps/admin_api/test/support/conn_case.ex
Issue/Task Number: T271
Small refactors and improvements of `ClientAuthPlug` and `UserAuthPlug` and its tests to cover all `:enable_client_auth` cases.
- ~Move `:enable_client_auth` check from `init/1` to `call/2` to support runtime config change~ No need to. I was coupling #178 and #179 together when I was doing that.
- Add tests to `ClientAuthPlugTest` and `UserAuthPlugTest` to cover all `:enable_client_auth` combinations
- Update moduledoc for `ClientAuthPlug` & `UserAuthPlug`
- Refined `UserAuthPlug.call/2` to be more specific when handling different kinds of auth headers:
- Added more `ClientAuthPlugTest` and `UserAuthPlugTest` tests. This should cover all combinations of `enable_client_auth: true` v.s. `false` and 4-part v.s. 2-part Authorization header.
- The refined …
> Improvements to ClientAuthPlug and UserAuthPlug

- apps/admin_panel/.gitignore
- apps/admin_panel/assets/config/webpack.js
- apps/admin_panel/config/config.exs
- apps/admin_panel/lib/admin_panel/endpoint.ex
- apps/admin_panel/test/admin_panel/test_assets/dist/index.html
Issue/Task Number: T268
This PR moves the AdminPanel's front-end build target to `/priv/static` as suggested by @sirn and [recommended by Phoenix](http://phoenixframework.org/blog/static-assets).
- Update .gitignore to ignore /priv/static
- Changed webpack's output to /priv/static
- Changed AdminPanel.Endpoint to serve static assets from /priv/static
Straightforward text replacements from /priv/dist to /priv/static
Running `mix omg.server` should produce successful front end build messages. Browse to `/admin` should return login page with static files served.
> Move AdminPanel front-end build target to /priv/static

- apps/local_ledger_db/priv/repo/migrations/20180430105449_update_predictable_minted_token_id.exs
Issue/Task Number: T263
Updated #172's migration to work on non-superuser DB users.
- Updated local ledger's minted token ID migration to work with extra columns instead of disabling foreign key constraint triggers.
#172 ran fine on dev & build machines because the ewallet apps were running with a postgres's superuser. Since running apps with a DB superuser must be avoided on servers, it does not make sense to have the migration requiring superuser privileges. Hence, this PR updates the migration script to avoid that by working with new columns, then replace them when ready instead.
Changes to the migration scripts must be avoided. But this is the case where failing on `develop` branch makes sense, so migrations are tested production-like environment and can be fixed before releasing a …
> Update local ledger migration to run with non-superuser permission

- apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
- apps/ewallet/test/ewallet/web/v1/event_handlers/event_test.exs
Issue/Task Number: T311
The logging of errors triggered by failed consumptions wasn't working as expected (The Logger couldn't format maps). This PR fixes that and add tests to ensure it doesn't happen again.
- Add `inspect` to format error map
- Add tests to ensure it's working as expected
> Fix failed logging of consumption errors

- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/router.ex
- apps/ewallet_api/priv/spec.yaml
- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Issue/Task Number: 278
This PR adds the `me.transfer` endpoint for clients.
It allows authenticated clients to transfer funds to an other address.
- Add `me.transfer` endpoint.
Pretty straightforward implementation.
The easiest way to test is to use the updated openapi spec.
na
> T278 me.transfer

- apps/ewallet_db/lib/ewallet_db/account.ex
- apps/ewallet_db/lib/ewallet_db/account_validator.ex
- apps/ewallet_db/test/ewallet_db/account_test.exs
- apps/ewallet_db/test/ewallet_db/account_validator_test.exs
Issue/Task Number: T314
This PR fixes `/account.update` returning maximum child level validation error even though updating the master account.
- Updated `Account.get_depth/1` to raise error if nil is provided as the account.
- Updated `AccountValidator.validate_account_level/2` to properly validate accounts with parent_uuid == nil
This error was caused because a master account would have `account.parent_uuid == nil`. When this nil is passed to `Account.get_depth/1`, the query would return `nil` back instead of a non-negative number.
This nil value that got passed back and evaluated in `depth >= child_level_limit` as `nil >= child_level_limit` which returns true (whyyyyyy) and hence passed right into `add_error/4` and thus the validation error.
`Account.get_depth(nil)` should raise an …
> Updating a master account should not return maximum child error

- apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
- apps/ewallet_db/lib/ewallet_db/transfer.ex
- apps/ewallet_db/lib/ewallet_db/validator.ex
- apps/ewallet_db/lib/ewallet_db/wallet.ex
Issue/Task Number: T337
Prevent burn wallet from sending transactions. This PR checks if the wallet is a burn wallet before allowing the creation of the transfer.
> Prevent burn wallet from sending transactions

- apps/ewallet/lib/ewallet/fetchers/credit_debit_record_fetcher.ex
- apps/ewallet/lib/ewallet/fetchers/wallet_credit_debit_assigner.ex
- apps/ewallet/lib/ewallet/fetchers/wallet_fetcher.ex
- apps/ewallet/lib/ewallet/gates/transaction_gate.ex
- apps/ewallet/test/ewallet/fetchers/credit_debit_record_fetcher_test.exs
- apps/ewallet/test/ewallet/fetchers/wallet_credit_debit_assigner_test.exs
- apps/ewallet/test/ewallet/fetchers/wallet_fetcher_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
- apps/ewallet_api/priv/spec.yaml
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Issue/Task Number: 17
This PR removes the `burn_balance_identifier` from credit/debit and instead adds `user_address` and `account_address` to let the user specify from/to which wallet the funds are taken/sent.
- Remove `burn_balance_identifier`
- Add `user_address` and `account_address`
- Add missing tests
> T17 update credit debit

- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
Saw this test randomly failing yesterday:
```
1) test consume/2 with user allows only one consume per user with four consumes at the same time (EWallet.TransactionConsumptionConsumerGateTest)
test/ewallet/gates/transaction_consumption_consumer_gate_test.exs:652
Assertion with == failed
code:  assert response == :max_consumptions_per_user_reached
left:  %{
__meta__: #Ecto.Schema.Metadata<:loaded, "transaction_consumption">,
__struct__: EWalletDB.TransactionConsumption,
```
This PR fixes that by checking that one of the responses is a valid consumption and the others are errors.
> Prevent random failure for consumption consumer gate

- apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/wallet_controller_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/wallet.ex
- apps/local_ledger/test/local_ledger/cached_balance_test.exs
Issue/Task Number: T346
Currently, the way the searcher works isn't great and it was causing the `account.get_wallets` and `user.get_wallets` endpoints to return unwanted results. For now, this PR removes the search step.
> Remove searching capabilities from Wallet Controller

- apps/admin_api/priv/spec.yaml
Some IDs on the API spec is still in the old format (uuid). This PR updates the spec to the sym_ULID format when appropriate.
- Updated spec.yml for ewallet_api
- Updated spec.yml for admin_api
Searched for uuid, checked that it's the incorrect format, changed the value.
Read the docs
> Fix API spec not up to date with the changed ID format

- apps/admin_api/mix.exs
- apps/admin_panel/mix.exs
- apps/ewallet/lib/ewallet/web/v1/serializers/category_serializer.ex
- apps/ewallet/mix.exs
- apps/ewallet_api/mix.exs
- apps/ewallet_db/mix.exs
- apps/local_ledger/mix.exs
- apps/local_ledger_db/mix.exs
- apps/url_dispatcher/mix.exs
Issue/Task Number: T312
This PR adds warnings_as_errors flag as suggested by @InoMurko so we detect warnings in our code.
- Add `elixirc_options: [warnings_as_errors: true]` to all app's Mixfiles
InoMurko originally suggested using `--warnings_as_errors` flag during compilation, but since we can add this as default in the Mixfile, I decided to add it to Mixfile instead so we can continue using `mix compile`
Run `mix compile` with warnings such as unused variable or alias should raise an error.
Deploy as usual
> Add warnings_as_errors flag to Mixfile

- apps/ewallet_db/lib/ewallet_db/transfer.ex
Issue/Task Number: T347
Since we have multiple nodes of the DB, there seem to be some randomly failing method in the Transfer insert flow. Basically, the retrieval after the insert fails because the record was "potentially" inserted in another node. This PR surrounds the insert/get flow with a transaction as an attempt to fix that.
- Add `Repo.transaction()` around in `insert`
> Surround Transfer retrieval after insert with transaction

- apps/ewallet/lib/ewallet/fetchers/transaction_request_fetcher.ex
- apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
- apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
- apps/ewallet/test/ewallet/fetchers/transaction_consumption_fetcher_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Issue/Task Number: T350
Currently, the client is responsible for formatting and storing data inside the QR code before decrypting and sending them. The server should take care of that to make it easier to upgrade the format. 
- Change `request_id` and `id` to `formatted_transaction_request_id`
- Add `formatted_id` to `TransactionRequest` serializer which can be directly encoded in a QR code and sent when consuming in `formatted_transaction_request_id`
> Added formatted_id to simplify transaction request flow

- apps/ewallet/lib/ewallet/formatters/transfer_formatter.ex
- apps/ewallet/lib/ewallet/gates/transfer_gate.ex
- apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
- apps/ewallet_db/lib/ewallet_db/transfer.ex
- apps/local_ledger/lib/local_ledger/entry.ex
- apps/local_ledger/test/local_ledger/entry_test.exs
- apps/local_ledger/test/local_ledger/transaction_test.exs
- apps/local_ledger_db/lib/local_ledger_db/entry.ex
- apps/local_ledger_db/priv/repo/migrations/20180606072241_rename_correlation_id_to_idempotency_token.exs
- apps/local_ledger_db/test/support/factory.ex
Issue/Task Number: T346
Attempting to fix [this issue](https://github.com/omisego/ewallet/issues/224) using Repo.Multi. Removed the retries as it wasn't a good solution. The code can be improved but I want to test it in staging, see if it actually fixes anything or not. My next step will be to try reproducing in local with a cluster.
- Use `Repo.Multi` to insert a Transfer and retrieve the latest inserted
- Ensure the local ledger can handle existing idempotency token by returning the existing entry instead or returning an error.
> Fixing Transfer retrieval after safe insert

- apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
- apps/admin_api/test/support/conn_case.ex
- apps/ewallet/lib/ewallet/gates/mint_gate.ex
- apps/ewallet/lib/ewallet/gates/transaction_gate.ex
- apps/ewallet/lib/ewallet/gates/transfer_gate.ex
- apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
- apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
- apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
- apps/ewallet_api/test/support/conn_case.ex
- apps/ewallet_db/lib/ewallet_db/transfer.ex
- apps/ewallet_db/lib/ewallet_db/validator.ex
- apps/ewallet_db/priv/repo/migrations/20180607103719_move_ledger_response_into_specific_fields.exs
- apps/ewallet_db/test/ewallet_db/transfer_test.exs
- apps/local_ledger_db/lib/local_ledger_db/errors/insufficient_funds_error.ex
Issue/Task Number: T346-3
The randomly failing `get_by_idempotency_token` seemed to have been fixed at the creation level, but was still failing when updating. I updated the code to simply return the updated record. I also removed the `ledger_response`and replace it with specific fields: `entry_uuid`, `error_code`, `error_description` and `error_data`.
- Remove `ledger_response`
- Return updated `transfer` directly instead of reloading it.
> Refactor ledger_response into multiple columns

- apps/ewallet/test/ewallet/fetchers/transaction_consumption_fetcher_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
- apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
- apps/ewallet/test/ewallet/web/v1/event_handlers/event_test.exs
- apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
Issue/Task Number: T383
Because the way ExUnit works, and with processes being decoupled from tests, we sometimes have race conditions where processes are still running. This PR adds a check to ensure a process has stopped running (or else will wait for it) after each test. If this doesn't fix all the tests, we'll change the `async` option to `false`.
```
1) test consume/1 with invalid parameters with invalid parameters (EWallet.TransactionConsumptionConsumerGateTest)
test/ewallet/gates/transaction_consumption_consumer_gate_test.exs:391
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.11737.0>}}
stacktrace:
test/ewallet/gates/transaction_consumption_consumer_gate_test.exs:13: EWallet.TransactionConsumptionConsumerGateTest.__ex_unit_setup_1/1 …
```
> Ensure processes started in tests are properly terminated

- apps/ewallet_db/priv/repo/migrations/20180607103719_move_ledger_response_into_specific_fields.exs
Issue/Task Number: T385
[Migrations](https://jenkins.omisego.io/job/omisego/job/ewallet/job/develop/) are failing! There seems to be something wrong with Cloak when passing `nil`. This PR ensures we only process the `ledger_response` if it isn't `nil`.
- Update migration with a check on the `ledger_response` value.
> Check that local_ledger is not nil before loading it with Cloak

- apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/account.ex
Issue/Task Number: T392
This PR fixes the issue that `/account.update` does not update account categories even though category_ids are passed.
- Update `Account.put_categories/3` to support both string and atom keys in attributes
Try update account categories by passing a different `category_ids` during `/account.update`
> Fix `Account.put_categories/3` to support both atom and string attribute keys

- apps/admin_api/test/admin_api/v1/controllers/category_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/account.ex
- apps/ewallet_db/lib/ewallet_db/category.ex
- apps/ewallet_db/lib/ewallet_db/helpers/input_attribute.ex
- apps/ewallet_db/test/ewallet_db/account_test.exs
- apps/ewallet_db/test/ewallet_db/category_test.exs
- apps/ewallet_db/test/ewallet_db/helpers/input_attribute_test.exs
Issue/Task Number: T402
This PR adds support for `/category.update` to update its associated accounts by passing `account_ids`
- Implemented `Category.put_accounts/3` and attach it to `Category.changeset/2`
- Refactored attribute retrieval into `EWalletDB.Helpers.InputAttribute.get/2`
This is basically the same implementation as the existing [`Account.put_categories/3`](https://github.com/omisego/ewallet/blob/develop/apps/ewallet_db/lib/ewallet_db/account.ex#L102-L120) but the other way around.
Also since the string/atom attribute retrieval is now used in multiple places, I refactored it into `EWalletDB.Helpers.InputAttribute.get/2`.
Make a request to `/category.update` with `{"account_ids": [], ...}`
> /category.update to support updating account_ids

- apps/local_ledger_db/lib/local_ledger_db/transaction.ex
- apps/local_ledger_db/test/local_ledger_db/transaction_test.exs
Issue/Task Number: T416
There was a problem in the way balances were calculated - if no credits ever happened, it would fail. For most cases, that was fine since you can't spend money you haven't received, but due to the possibility of passing `since: date` to that function, it was failing if only debits happened after `date`.
This PR fixes it!
> Fix transaction calculation fail

- apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/transaction_controller_test.exs
Issue/Task Number: T427
This PR fixes a 500 error being returned when trying to send funds from a burn balance using `/transaction.create`.
- Add a test to ensure this is now working
- Add a new function to handle changeset return with errors
> Fix 500 when sending funds from burn balance

- apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Issue/Task Number: T429
Only `type` and `token_id` should be required to create transaction requests. However, currently some functions expect to see `correlation_id`, `amount` and `address` in the arguments. This PR removes those unnecessary checks.
- Modify the min params test for transaction request gate.
- Remove unneeded params check in `TransactionRequestGate` functions
> Allow transaction_request to be created with only token_id and type

- .dialyzer_ignore
- apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/admin_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/status_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/transfer_controller.ex
- apps/ewallet/lib/ewallet/cli.ex
- apps/ewallet/lib/ewallet/gates/mint_gate.ex
- apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
- apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
- apps/ewallet/lib/ewallet/policies/account_policy.ex
- apps/ewallet/lib/ewallet/web/embedder.ex
- apps/ewallet/lib/ewallet/web/preloader.ex
- apps/ewallet/lib/ewallet/web/v1/serializers/key_serializer.ex
- apps/ewallet/test/ewallet/web/embedder_test.exs
- apps/ewallet_api/lib/ewallet_api/global/controllers/status_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/self_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/status_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
- apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
Describe what your Pull Request is about in a few sentences. This is a global description that should tell people what your PR is all about. Don't go too much into details here.
- Types and 5 other issues added to the ignore file. I think `account.ex` and `user.ex` issues are both related to arc_ecto issues.
- Lots of dead code removed
- Preloader can return a list of changeset which was ignored previously (it shouldn't happen but it has to be handled)  
Couldn't address dependency issues with avatar upload.
No special requirement.
What's left is:
If someone can run dialyzer and let me know if the issues in `transaction_consumption_controller.ex` which uses `EWallet.Web.Embedder` macro are causing the same problems? As said in Gitter, I once rewrote the `embed` function …
> addressing dialyzer reported issues

- apps/ewallet_db/lib/ewallet_db/wallet.ex
- apps/ewallet_db/priv/repo/migrations/20180620100944_remove_token_uuid_from_wallets.exs
- apps/ewallet_db/test/support/factory.ex
Issue/Task Number: T432
Wallets were originally supposed to potentially belong to a token where newly minted tokens would go. This behavior has been changed (it goes to the master account now) but we never removed `token_uuid` from `Wallet` which is now leading to confusion.
- Generate migration to remove `token_uuid` from `wallet` table
> Remove token from Wallet

- apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
- apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
Issue/Task Number: T433
This PR removes unneeded params check from transaction request consumption and fix a bug returning a 500 when the amount used was the one coming from the transaction request.
- Remove `address` as a mandatory param when consuming as a user
- Fix returned value when validating the amount of request/consumption
> Fix consumptions unneeded params

- README.md
- apps/ewallet/lib/ewallet/seeders/cli_seeder.ex
- apps/ewallet/lib/mix/tasks/omg.seed.ex
- apps/ewallet/test/ewallet/web/search_parser_test.exs
- apps/ewallet_db/priv/repo/reporters/seeds_test.exs
- apps/ewallet_db/priv/repo/seeds_test/00_account.exs
- apps/ewallet_db/priv/repo/seeds_test/00_role.exs
- apps/ewallet_db/priv/repo/seeds_test/01_user.exs
- apps/ewallet_db/priv/repo/seeds_test/02_membership.exs
- docs/setup/env.md
- docs/tests/e2e.md
Issue/Task Number: 393
This PR adds a new option to the `mix seed` command in order to generate the needed data to run acceptance tests
- Add `mix seed --test --yes` command
- `--test` seeds 2 admins and a base account
- `--yes` skips all prompts
- Add a few environment variables to limit the use of this seed
To run the test seed in local, use:
`E2E_ENABLED=true mix seed --test --yes`
> Database seed for acceptance testing

- apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
- apps/admin_api/test/admin_api/v1/views/api_key_view_test.exs
- apps/ewallet/lib/ewallet/web/v1/serializers/api_key_serializer.ex
- apps/ewallet_db/lib/ewallet_db/api_key.ex
Issue/Task Number: T323
Add an `/api_key.update` endpoint to allow admin to enable/disable keys.
- Add `/api_key.update`
- Update OpenAPI spec
Call `/api_key.update` with an `id` and `expired` set to `true` or `false`.
See OpenAPI spec for more info.
> Allow API keys to be disabled/enabled

- apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
- apps/ewallet/lib/ewallet/fetchers/user_fetcher.ex
- apps/ewallet/test/ewallet/fetchers/user_fetcher_test.exs
Issue/Task Number: T453
This PR is a follow up of [this one](https://github.com/omisego/ewallet/pull/268).
A few things were wrong and they are fixed in this PR
- Added a new `UserFetcher` in order to fetch a user from a `provider_user_id` or a `user_id`
- Added support for both `provider_user_id` and `user_id` on `user.get_transaction_consumptions`
- Fixed swagger
- Duplicated tests for server_auth
- Renamed `transaction_request_id` to `formatted_transaction_request_id` for `transaction_request.get_transaction_consumptions`
> Fixes transaction request and consumptions

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/mint_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/mint_controller_test.exs
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
Issue/Task Number: T411
This PR fixes the error messages and description returned in the JSON.
- Replace the %{xxx} with the actual value in the description
- Add the error instead of `null` in messages
> Fix null in error messages / Fix error description

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transfer_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transfer_controller_test.exs
- apps/ewallet/lib/ewallet/formatters/amount_formatter.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/formatters/amount_formatter_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Issue/Task Number: T449
This PR improves the display amount in `insufficient_funds` errors.
There was 2 issues in the current implementation:
- trailing zeros (ie: 10000.0)
- decimals limited to 1 (ie: 1234.5), so we were missing accuracy if the subunit_to_unit was bigger than 10
- Created a `AmountFormatter` that takes care of formatting amount for display
- The number of decimals is now dynamic depending on the subunit_to_unit given
- The string is formatted so if it ends with '.0' it's truncated
> Improve amounts displayed in insufficient funds error

- apps/ewallet_db/priv/repo/migrations/20180626055050_update_constraint_names.exs
Issue/Task Number: T330
Fixes quite a few constraint names that were out of sync due to columns being renamed over time.
- Add a new DB migration that aligns the constraint names with the latest table column names
I decided to use `execute()` with raw SQLs due to readability and not having to depend on column properties.
This `ALTER TABLE ... RENAME CONSTRAINT ...` is available since postgres 9.1 released in 2011 so it should be safe enough.
All constraints in LocalLedgerDB looks correct so there's no migration for that.
Run `mix ecto.migrate`.
To check all the constraint names, run the following SQL:
```sql
SELECT
tc.constraint_name,
tc.table_name || '.' || kcu.column_name AS table_column
FROM 
information_schema.table_constraints AS tc 
JOIN information_schema.key_column_usage AS kcu
ON …
```
> Rename constraint names to align with latest table schemas

- apps/admin_api/test/admin_api/v1/channels/address_channel_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transfer_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transfer_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
- apps/ewallet/test/ewallet/fetchers/address_record_fetcher_test.exs
- apps/ewallet/test/ewallet/fetchers/wallet_credit_debit_assigner_test.exs
- apps/ewallet/test/ewallet/fetchers/wallet_fetcher_test.exs
- apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
- apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
- apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/types/wallet_address.ex
- apps/ewallet_db/lib/ewallet_db/wallet.ex
- apps/ewallet_db/priv/repo/migrations/20180627073155_update_genesis_address_in_wallet.exs
- apps/ewallet_db/test/ewallet_db/types/wallet_address_test.exs
- apps/ewallet_db/test/ewallet_db/wallet_test.exs
- apps/ewallet_db/test/support/factory.ex
- apps/local_ledger_db/mix.exs
- apps/local_ledger_db/priv/repo/migrations/20180627100553_update_genesis_address_in_wallet.exs
Issue/Task Number: T357
This PR updates address format to align with [OIP-3](https://github.com/omisego/OIP/issues/3).
- Add new Ecto type `EWalletDB.Types.WalletAddress`
- Change `EWalletDB.Wallet` to use `EWalletDB.Types.WalletAddress` instead of plain string
- `EWalletDB.Wallet` autogenerates the address if one is not given
- `EWalletDB.Wallet`'s address is immutable once set
- Mainly the added logic is in `EWalletDB.Types.WalletAddress` and implemented as a [custom Ecto type](https://hexdocs.pm/ecto/Ecto.Type.html).
- Address is saved in database with non-alphanumerics stripped so that it's consistent for searching and manipulating. Each provider can add non-alphanumerics separators or send them over unstripped as they wish.
- No migrations were added since the old addresses are still …
> Update address format to align with OIP-3

- apps/ewallet_db/lib/ewallet_db/token.ex
- apps/ewallet_db/priv/repo/migrations/20180627115719_update_token_id_to_lowercase.exs
- apps/ewallet_db/test/ewallet_db/token_test.exs
- apps/local_ledger_db/priv/repo/migrations/20180627122112_update_id_to_lowercase_in_token.exs
Issue/Task Number: T401
This PR fixes the token ID generation so that the ULID part is in lower case.
For example, `tok_ETH_01CH0AP3NQYSAWHHZNGJCC6WZ4` should be `tok_ETH_01ch0ap3nqysawhhzngjcc6wz4`.
- Updated `EWalletDB.Token` to lower case the ULID part before saving.
- Added DB migrations to update existing token IDs in `ewallet_db` and `local_ledger_db`
Straight forward lower-casing during token insert.
Try `/token.create`.
`mix ecto.migrate` after deploy.
> Fix Token ID generation should generate the ULID part in lower case

- apps/ewallet/lib/ewallet/application.ex
- apps/ewallet/lib/ewallet/formatters/amount_formatter.ex
- apps/ewallet_db/lib/ewallet_db/token.ex
- apps/ewallet_db/lib/ewallet_db/transaction.ex
- apps/ewallet_db/test/ewallet_db/token_test.exs
- apps/ewallet_db/test/ewallet_db/transaction_test.exs
- mix.exs
Issue/Task Number: 420
This PR limits the maximum amount (from and to) that can be passed to a transaction.
Also fixes an issue with the current implementation of the `AmountFormatter` that was losing precision with big numbers
- Limit `from_amount` and `to_amount` to be less than `100_000_000_000_000_000_000_000_000_000_000_000`
This constraint comes from a limitation of `swift` where we can't easily decode numbers with more than 38 digits.
> Add amount validation on transactions

- apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/category_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/category_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/category.ex
- apps/ewallet_db/test/ewallet_db/category_test.exs
Issue/Task Number: T394
This PR prevents category from being deleted if there are accounts still associated with the category. Thanks to @mederic-p for spotting this.
- Update `EWalletDB.Category.delete/1` to check for account emptiness before deleting the category
- Update `AdminAPI.V1.CategoryController` to handle `{:error, :category_not_empty}`
- Add `:category_not_empty` error to AdminAPI's ErrorHandler
Simple logic addition to `EWalletDB.Category.delete/1` to check for associated accounts before soft deleting the category.
Try `/category.delete` on a category that still has one or more accounts associated.
Code changes only. No changes to the DB or API request/response formats.
> Prevents category deletion if accounts are still associated

- apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
This PR fixes random test failures due to asserting a specific position in a list.
- Update `AdminAPI.V1.ProviderAuth.WalletControllerTest` to use `Enum.any?/2` instead of asserting on `Enum.at/2`
Since some assertions do not imply any sorting, asserting on `Enum.at/2` is replaced with `Enum.any?/2`.
Example errors:
```
1) test /wallet.create inserts a new burn wallet for an account (AdminAPI.V1.ProviderAuth.WalletControllerTest)
test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs:387
Assertion with == failed
code:  assert Enum.at(wallets, 3).address() == response["data"]["address"]
left:  "druk472088053824"
right: "fazd729024613357"
stacktrace:
test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs:406: (test)
```
Run `mix test`. …
> Fix errors from asserting a non-deterministic list position

- apps/admin_panel/assets/src/services/adminService.js
When accepting invite, we need to call a request to create an account. This request is not an authenticated request which makes only logged in users will be able to accept invite.
- Change endpoint to `unauthenticated`
-
Invite someone, and accept the link to create a new password and login.
> use unauthenticated request

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
- apps/ewallet/lib/ewallet/application.ex
- apps/ewallet/lib/ewallet/exchange/exchange.ex
- apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/mix.exs
- apps/ewallet/test/ewallet/exchange/exchange_test.exs
- apps/ewallet/test/ewallet/fetchers/amount_fetcher_test.exs
- apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
- apps/ewallet_db/test/ewallet_db/exchange_pair_test.exs
- mix.exs
Issue/Task Number: T454
This PR prevents creating or updating an exchange pair with a rate of zero or below.
- Update `ExchangePair`'s changeset to validate for a rate greater than 0
- Added tests for the controllers
Straightforward use of [`Ecto.Changeset.validate_number/3`](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_number/3)
Try `/exchange_pair.create` or `/exchange_pair.update` with `rate` of 0 or below. They should return `invalid_parameter` error with the description explaining the validation error.
Code changes only. No changes to the DB schema or API request/response format.
> Prevents an exchange rate of 0 or below

- README.md
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
- apps/ewallet/lib/ewallet/formatters/transaction_formatter.ex
- apps/ewallet/test/ewallet/formatters/transaction_formatter_test.exs
- docs/design/transactions_and_entries.md
- mix.exs
Issue/Task Number: T467
This PR fixes the entries generation for cross-token transfers that involve `from` or `to` address being the exchange wallet itself.
- Add support for cross-token transfers from/to an exchange wallet into `EWallet.TransactionFormatter`
- Add tests to validate the change in `TransactionFormatterTest` as well as transaction controller tests.
- Fill in some missing test cases between admin user and provider requests.
Because usual cross-token transfers require 4 debit/credit entries (2 for moving `from_token` into the exchange account, 2 for moving `to_token` out of the exchange account), so the existing `TransactionFormatter` generates a pair of debit/credit that goes to the same wallet address when an exchange wallet is also used as `from` or `to` address.
This is …
> Allow cross-token transactions from/to exchange wallet

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/types/integer.ex
This PR fixes an issue where the load!/1 function was crashing when provided with nil.
> Fix token stats when token not minted yet

- apps/admin_api/lib/admin_api/invites/inviter.ex
- apps/admin_api/test/admin_api/v1/plugs/admin_api_auth_plug_test.exs
- apps/admin_api/test/support/conn_case.ex
- apps/ewallet_db/lib/ewallet_db/api_key.ex
- apps/ewallet_db/lib/ewallet_db/auth_token.ex
- apps/ewallet_db/lib/ewallet_db/forget_password_request.ex
- apps/ewallet_db/lib/ewallet_db/helpers/crypto.ex
- apps/ewallet_db/lib/ewallet_db/invite.ex
- apps/ewallet_db/lib/ewallet_db/key.ex
- apps/ewallet_db/test/ewallet_db/helpers/crypto_test.exs
- apps/ewallet_db/test/ewallet_db/key_test.exs
- apps/ewallet_db/test/support/factory.ex
Issue/Task Number: T494
This PR switches away from Bcrypt to SHA2 for hashing of the secret keys.
All current access/secret keys should be deleted since they will not be usable anymore.
> Switch to SHA2 for secret key hashing

- apps/admin_api/test/support/channel_case.ex
- apps/ewallet_api/test/support/channel_case.ex
Just an attempt to see if that fixes some stuff (even tho it shouldn't) since I didn't experience failures with that setting for 10builds + when trying it out last time.
> Add back async: false at the channel case level to fix random failures

- apps/admin_api/config/config.exs
- apps/admin_api/config/prod.exs
- apps/admin_api/lib/admin_api/invites/inviter.ex
- apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
- apps/admin_api/test/admin_api/invites/inviter_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/forget_password_request.ex
Issue/Task Number: T484
This PR whitelists only the configured `BASE_URL` environment variable to be used for `redirect_url` when sending invitation and forget password emails. Thanks to the spotting by @jarindr.
- Add `base_url: System.get_env("BASE_URL")` as an :admin_api env
- Update `AdminAPI.Inviter` to whitelist redirect_url
- Update `AdminAPI.V1.ResetPasswordController` to whitelist redirect_url
Checking against the `BASE_URL` still allows attacks from the same base url, but given the un-likelihood of such setup, this PR should be sufficient for the time being.
The url checks for user invitation and forget password is not at the same level: `Inviter` vs. `ResetPasswordController`. It could have been refactored but given the amount of code changes needed it's not worth it towards …
> Whitelist only BASE_URL for invitation emails

- apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/api_key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/api_key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
- apps/admin_api/test/admin_api/v1/views/key_view_test.exs
- apps/ewallet/lib/ewallet/web/v1/serializers/key_serializer.ex
- apps/ewallet/test/ewallet/web/v1/serializers/key_serializer_test.exs
- apps/ewallet_db/lib/ewallet_db/key.ex
- apps/ewallet_db/priv/repo/migrations/20180706054113_add_expired_to_key.exs
- apps/ewallet_db/priv/repo/seeds/01_user.exs
- apps/ewallet_db/priv/repo/seeds_sample/00_admin_panel_user.exs
- apps/ewallet_db/test/ewallet_db/api_key_test.exs
- apps/ewallet_db/test/ewallet_db/key_test.exs
- apps/ewallet_db/test/support/factory.ex
- apps/ewallet_db/test/support/schema_case.ex
Issue/Task Number: T463
This PR adds `/access_key.update` allowing enable/disable of access keys.
- Updated the `Key`'s controller, view, serializer and their tests to support `/access_key.update`
- Updated Open API spec for `/access_key.update`
- Added typespecs to `EWalletDB.Key`
- Added missing `APIKey.update/2` tests
A straight-forward addition of `/access_key.update` endpoint.
Try `/access_key.update`:
**Request:**
```sh
curl POST \
10.5.10.10:4000/api/admin/access_key.update \
-H "Authorization: OMGProvider $(echo -n "access_key:secret_key" | base64 | tr -d '\n')" \
-d '{
"id": "key_01chqcgrggh1hxja6y7hnqwavm",
"expired": true
}' \
-v -w "\n" | jq
```
**Response:**
```json
{
"version": "1", …
```
> Add /access_key.update

- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/ewallet_api/priv/spec.json
- docs/api_specs.md
Fixes the broken Admin API's `spec.yaml`.
- Fix `admin_api/priv/spec.yaml`
- Regenerate `spec.json` for both Admin API and eWallet API
- Update `docs/api_specs.md` for a better Copy-And-Paste programming
I screwed up the spec's type. Period.
`/api/admin/docs` and `/api/docs` should be rendered without errors.
No DB changes. No external API changes.
> Fix broken spec.yaml due to invalid type

- apps/admin_api/lib/admin_api/v1/serializers/auth_token_serializer.ex
- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_auth_controller_test.exs
Issue/Task Number: 510
This PR adds the `role` attribute to the auth token response.
This will allow the admin to know if we should display the action buttons or not depending on the role of the user.
- Add `role` to `auth_token_serializer`
- Update spec (re-generate outdated `json` spec)
> Add role to auth token

- apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
This PR fixes events not being sent in the consumption controller in the client API (detected thanks to our E2E tests, yay)
> Send events when consuming in client API

- apps/ewallet_db/lib/ewallet_db/transaction_request.ex
- apps/ewallet_db/priv/repo/seeds/01_user.exs
- apps/ewallet_db/priv/repo/seeds_sample/00_token.exs
- apps/ewallet_db/priv/repo/seeds_sample/00_user.exs
- apps/ewallet_db/priv/repo/seeds_sample/01_exchange_pair.exs
- apps/ewallet_db/priv/repo/seeds_sample/30_transaction_request_and_consumption.exs
- apps/ewallet_db/priv/repo/seeds_test/01_user.exs
- apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Issue/Task Number: T505
This PR adds account-user linking, and more seeds including users' initial funds, exchange pairs, transaction requests and consumptions. Mainly this should help with see sampling data on the Admin Panel.
- Add account-user linking during user seed
- Add funds to user wallets during user seed
- Add new seed for exchange pairs
- Add new seed for transaction requests and consumptions
Straight forward seeds
Run `mix seed --sample` to see the additional seeds. The `mix seed` has no new changes.
See below for screenshots of the added seeds.
Initial user funds:
Exchange pairs:
Transaction requests:
Transaction consumptions:
No API changes. No DB schema changes.
> New seed: initial user funds, exchange pairs, transaction requests and consumptions

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
- apps/ewallet_db/priv/repo/seeds_test/01_user.exs
This PR updates the seed so that it relies on master account uuid from runtime instead of compile-time.
- Updated `apps/ewallet_db/priv/repo/seeds_test/01_user.exs`
Because during compile time, master account may not exist yet, we cannot rely on `account_uuid` then. This PR updates it so that a static value (`account_name: "master_account"`) is used instead to find the master account.
Original error:
```ex
$ E2E_ENABLED=true mix seed --test --yes
** (UndefinedFunctionError) function nil.uuid/0 is undefined or private
nil.uuid()
_build/dev/lib/ewallet_db/priv/repo/seeds_test/01_user.exs:9: (module)
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(elixir) lib/code.ex:629: Code.load_file/2
lib/ewallet/seeders/seeder.ex:45: EWallet.Seeder.mod_from/1
(elixir) …
```
> Move E2E seed's master account value from compile-time to runtime

- apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
Issue/Task Number: #345 
closes #345 
E2E tests found out that sending a `nil` email when resetting a password would result in a `500` error. This is now fixed in this PR by checking that the `email` (and `redirect_url`) are not `nil`.
- Add test to reproduce the issue
- Add guard clause to protect the controller function
> Ensure email and redirect_url are not nil when resetting a password

- apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
Issue/Task Number: #346 
closes #346
Fallback pattern matching functions were missing for the `upload_avatar` endpoints, resulting in a 500.
- Add tests to reproduce the error for accounts and admins
- Add the fallbacks
> Add fallback for upload_avatar endpoints

- apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/token_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Issue/Task Number: #347 
closes #347
We currently have `token_id_not_found` and `token_not_found`. This PR removes the former and replaces all instances with the latter.
> Remove token_id_not_found error

- apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
Issue/Task Number: #349 
closes #349 
Sending `null` for the `email` field when calling `/account.assign_user` would result in a `500` error. This PR fixes it.
- Add test to reproduce the issue
- Refactor assign function
- Handle `nil` email
> Handle nil email submitted for assign_user endpoint

- apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
- apps/ewallet_db/lib/ewallet_db/key.ex
- apps/ewallet_db/test/ewallet_db/key_test.exs
Issue/Task Number: 371
closes #371
Currently, disabled keys can still be used to authenticate requests. This PR fixes that by only using non-expired keys.
- Add test
- Fix key authenticate function
> Prevent the use of disabled keys

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
Issue/Task Number: 377
Closes #377
It seems the issue has been fixed in #329, but this PR adds a test to ensure it doesn't come back in the future.
- Add a test with 22 decimals for the `subunit_to_unit` when creating a token
> Add test to ensure subunit_to_unit > 18 does not return 500

- apps/url_dispatcher/lib/mix/tasks/omg.server.ex
Issue/Task Number: 
Closes: #381 
This PR fixes the issue with `mix omg.server --no-watch` failing to run with the following error:
```ex
$ mix omg.server --no-watch
** (Mix) Could not invoke task "omg.server": 1 error found!
--no-watch : Unknown option
```
- Removed adding `args` back during `Mix.Tasks.Omg.Server` starting up.
The mix task expects the argument to be removed once it's handled so this PR removes `++ args` that's causing the issue.
Run `mix omg.server --no-watch` should start the server up successfully.
No changes to API or database schema.
> Fix unknown --no-watch option error

- docs/setup/bare_metal.md
Closes #384
This PR adds the missing test database setup step to the bare-metal setup and explanation on the use of bash parentheses.
- Add explanation about parentheses before yarn install
- Add test database setup step
N/A
Readme changes only.
Textual changes only. No API and DB changes.
> Add test database setup to bare-metal readme & explanation on bash parentheses

- apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
- apps/admin_panel/assets/src/omg-transaction-panel/index.js
Issue/Task Number: #370 
Fix bug for link account and cache.
- Fix link bug.
- Fix cache loading.
> fix bugs link typo and cache

- README.md
Closes #386
This PR removes Vagrant setup instructions from README as Goban bootstrapper needs to be updated.
- Removed Vagrant setup from README.md
As Goban requires quite a bit of refresh. The instructions to use Vagrant is removed temporarily so it does not mislead users to try it out.
N/A
N/A
> Remove vagrant setup from readme temporarily

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
Closes #378.
This PR fixes the error description when the description contains `*_uuid` field names, it should convert them to `_id` field names.
- Added a call to `replace_uuids/1` while building the error description
- Added an ExchangePairController test to cover this case
Since we never expose `*_uuid` fields to the API, this is an umbrella fix on the ErrorHandler so it always convert to `_id` field names.
Try `/api/admin/exchange_pair.create` with the same `from_token_id` and `to_token_id` or use the values as reported in #378. The error message should be about `from_token_id` and `to_token_id` and no longer the `*_uuid` fields.
No DB changes. API: Only impacts the error description text.
> Fix error description not converting field names from _uuid to _id

- apps/admin_api/priv/spec.yaml
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/ewallet/lib/ewallet/fetchers/user_fetcher.ex
Issue/Task Number: #402 
closes #402
The params for `/user.get_transaction_consumptions` were not consistent with the rest of the API. This PR fixes it.
- Add support for `id` 
- Add tests
- Keep support for `user_id` through the `UserFetcher` to not break the API.
> Switch user_id to id for /user.get_transaction_consumptions

- apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
Issue/Task Number: 416
closes #416
Amount sent as float or `nil` were not returning errors as expected, and instead were raising `500` errors. This PR fixes that.
- Handle `float` amounts when consuming (returns an error)
- Handle `nil` amount when consuming and request amount is also `nil` (returns an error)
> Properly handle invalid amounts for consumption

- apps/admin_panel/assets/src/socket/connector.js
Issue/Task Number: #420 
This PR fix websocket log connection error when connecting to websocket too fast.
- handle case socket not init.
Open browser first time, login and see logs saying websocket will be queued if socket is not connected yet.
> Fix log error for websocket

- apps/admin_api/lib/admin_api/emails/forget_password_email.ex
- apps/admin_api/lib/admin_api/invites/invite_email.ex
- apps/admin_api/test/admin_api/emails/forget_password_email_test.exs
- apps/admin_api/test/admin_api/invites/invite_email_test.exs
Closes #425 
Encodes the email address before putting it into the `redirect_url`.
- Do a `URI.encode_www_form/1` before replacing the email address into the `redirect_url`.
- Changed test email addresses to `@example.com` to be more neutral
- Changed `ForgetPasswordEmailTest` to use `create_email/2` instead of `setup()` so different emails can be tested
N/A
Invite a new admin user or forget password from an email with `+` sign. The password should be able to set successfully with the url in the email.
No changes to the API or DB.
> Fix unencoded email invite url

- apps/ewallet/lib/ewallet/fetchers/transaction_consumption_fetcher.ex
- apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
- apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
- mix.exs
Added a more strict Dialyzer setting.
Fixed the reported issues from master.
Fixed specs 
/
Nothing mayor.
> strict dialyzer analysis

- apps/admin_api/mix.exs
- apps/admin_panel/mix.exs
- apps/ewallet/mix.exs
- apps/ewallet_api/mix.exs
- apps/ewallet_db/mix.exs
- apps/local_ledger/mix.exs
- apps/local_ledger_db/mix.exs
- apps/url_dispatcher/mix.exs
Issue/Task Number: 431
closes #431
This PR removes the warnings that came with the new version of Elixir (1.7.0).
- Fix quoted atoms which were raising warnings
> Fix Elixir 1.7.0 warnings

- docs/setup/bare_metal.md
- docs/setup/macos/brew_install_dependencies.md
Adds a quick dependency installation guide for Homebrew user.
- Add a new .md file that explains how to setup the dependencies via Homebrew
- Moved node up before yarn
N/A
N/A
N/A
> Add dependency setup guide via Homebrew

- apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
Issue/Task Number: 460
This is a small fix to improve the performances of consumption loading. It was slowed down due to the huge amount of data loaded to have accurate consumptions. Preloading fixes the problem, but the overall preloading handling should be refactored in a cleaner way.
I'm thinking we might want to put the actual list of fields to preload in the serializers, and build the final list for an endpoint depending on which serializer it uses (and the ones nested under it).
- Preload everything for consumptions.
> Preload all required fields for consumptions

- apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
Closes #465
This PR fixes the issue when a user invitation fails if the invite is retried. This would happen when an admin invites a user, did not receive the email or wants to resend the invitation for other reasons, the admin would receive an error instead.
- Fixed the `Inviter.send_email/2` receiving a module instead of the email template function
N/A
Try to invite a new user via the admin panel, then invite the same user for the second time, the invite should be successful now.
No DB or API changes.
> Fix inviting a user failing on the 2nd time

- apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
- apps/admin_panel/assets/src/omg-page-users/index.js
Issue/Task Number: #470 
When trying to transfer with pre-fill address of transaction modal, you cannot change that address due to react component lifecycle.
- Fix prefill address bug
- Add email field in user
Go to transfer modal from address detail page, and change address after pre-fill address.
> Fix prefill address bug

- apps/admin_api/lib/admin_api/v1/controllers/invite_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/user.ex
- apps/ewallet_db/test/ewallet_db/user_test.exs
Closes #472 
This PR fixes the issue where an admin could not login after the invitation has been accepted.
- Added a step so that user's `is_admin` flag is set to `true` right after the invitation is successfully accepted.
N/A
Invite a new admin and follow the email verification process. After the email is verified successfully the admin should be able to login to the Admin Panel.
No changes to the DB or API.
> Fix admin not being able to login after accepting the invitation

- apps/ewallet/test/ewallet/web/inviter_test.exs
- apps/ewallet/test/support/mock_invite_email.ex
Closes #453 
Replace `EWallet.Web.InviteTest`'s dependencies on `AdminAPI.InviteEmail` and `EWalletAPI.VerificationEmail` to `EWallet.Web.MockInviteEmail`.
- Added a new `EWallet.Web.MockInviteEmail`
- Replaced occurences of `AdminAPI.InviteEmail` and `EWalletAPI.VerificationEMail` in `EWallet.Web.InviteTest` with `EWallet.Web.MockInviteEMail`
Although tests are passing, the `EWallet` modules should not depend on `AdminAPI` nor `EWalletAPI` modules. Hence the replacement with `EWallet.Web.MockInviteEmail`.
This has impact on the tests only.
No DB or API changes
> Fix EWallet tests' dependency on AdminAPI and EWalletAPI module

- docs/setup/docker.md
Closes #442
This PR streamlines the docker setup guide as per feedbacks from the various workshops, #439 and #442.
- Updated docker setup guide
Before, the guide branches off at step one for the user to pick between docker compose and plain docker, then they converge back in step 2. This is difficult to follow so now the option branches off right at the beginning and there's no convergence in the middle.
The commands have so been updated with more default values to make the setup easier.
Follow the commands in the changed guide.
Changes to user documentation only.
> Streamline docker setup guide

- apps/ewallet_db/priv/repo/migrations/20181008085802_rename_unicity_constraint_for_consumption_correlation_id.exs
- apps/ewallet_db/test/ewallet_db/transaction_consumption_test.exs
Issue/Task Number: #491
closes #491
This PR fixes the error below, which was due to a unicity constraint improperly named on the `transaction_consumption` table.
```
Request: POST /api/admin/transaction_request.consume
** (exit) an exception was raised:
** (Ecto.ConstraintError) constraint error when attempting to insert struct:
* unique: transaction_request_consumption_correlation_id_index
If you would like to convert this constraint into an error, please
...
```
- Rename the unique index for `correlation_id`
> Prevent 500 when sending same correlation ID with consumptions

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/ewallet/lib/ewallet/web/v1/overlays/transaction_consumption_overlay.ex
Issue/Task Number: 496
closes #496
Exchange pair tokens weren't properly loaded in transaction consumptions > transactions. This PR fixes it.
- Preload exchange pair from transaction consumptions
- Add test
> Preload exchange pair in consumptions

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/test/ewallet/web/orchestrator_test.exs
Closes #501
This PR adds the missing `MatchAnyParser` to `EWallet.Web.Orchestrator.build_query/3`.
- Add `MatchAnyParser.to_query/3` to `Orchestrator.build_query/3`'s flow
- Changed the default arguments for `Orchestrator` functions from `attrs \\ nil` to `attrs \\ %{}`
- Add tests for `EWallet.Web.Orchestrator`
- Straightforward adding of `MatchAnyParser.to_query(...)` to `Orchestrator.build_query/3` pipe.
- The default arguments for `Orchestrator` functions are changed from `attrs \\ nil` to `attrs \\ %{}` since the implementation expects an attribute map.
```
curl 10.5.10.10:4000/api/admin/transaction.all \
-H "Authorization: OMGAdmin dXNyXzAxY3Y2cm0xZTZzNnFmZjcwcHBnMnAwdmZzOm1CQjVfTzhTTnVXYjAxWFZ6eDdRVTBJUTRuUXc1S1htQ1JzbkVNMHZGaUU=" \
-H …
```
> Add match_any filter to Orchestrator

- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/web/orchestrator_test.exs
Closes #505
This PR fixes the internal server error that is returned when attempting to filter records with a field that's not allowed.
This PR is based on the changes in #501 so it's based out of #501 until merged.
- Handles when `{:error, :not_allowed, field}` is returned by the parser in `EWallet.Web.Orchestrator`
N/A
```
curl 10.5.10.10:4000/api/admin/transaction.all -H "Accept: application/vnd.omisego.v1+json" -H "Authorization: OMGAdmin <truncated>" -H "Content-Type: application/json" -d '{
"match_all": [
{
"comparator": "eq",
"field": "1232131",
"value": true
}
],
"page": 1,
"per_page": 10,
"sort_by": "name",
"sort_dir": "asc"
}' -v -w "\n"
```
Should now return a `client:invalid_parameter` error rather than an `internal_server_error` error.
No DB or API changes.
> Fix internal server error when trying to filter a field that's not allowed

- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/lib/ewallet/web/v1/overlays/wallet_overlay.ex
- apps/ewallet/test/ewallet/web/orchestrator_test.exs
Closes #513
This PR fixes the issue with filtering a disallowed field on `/api/admin/account.get_wallets`.
- Updated `Orchestrator.build_query/3` to use `with` clause instead of pipes to catch errors mid-way.
- Fixed `WalletOverlay` that should use `self_filter_fields()` instead of `default_preload_assocs()` for figuring out the allowed filter fields.
Because `Orchestrator.build_query/3` was using pipes, this makes it hard to handle error if it is returned midway. This PR changed it to use `with` clauses.
Also, `WalletOverlay` was using `default_preload_assocs()` to build the filters instead of `self_filter_fields()`.
Making a request like following should return the proper results:
```sh
curl 10.5.10.10:4000/api/admin/account.get_wallets \ …
```
> Fix error 500 when trying to filter a disallowed field on /api/admin/account.get_wallets

- apps/ewallet/lib/ewallet/policies/transaction_request_policy.ex
- apps/ewallet_config/config/config.exs
- apps/ewallet_db/priv/repo/seeds_test/01_user.exs
- apps/ewallet_db/priv/repo/seeds_test/10_setting.exs
- docs/setup/advanced/env.md
Issue/Task Number: 525
Closes #525 
This PR adds the insertion of a normal user in addition to the 2 test admins that were inserted.
This is required to test the standalone user login in the E2E test environment.
- Insert a new user when running the test seeds
- Add 2 new environment variables that allow the user's admin and password to be specified:
- `E2E_TEST_USER_EMAIL`
- `E2E_TEST_USER_PASSWORD`
N/A
Run the test seeds: `E2E_ENABLED=true mix seed --test --yes`
New env variable to setup in the E2E environment
> Add the insertion of a normal user to the test seed

- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_calculation_controller_test.exs
- apps/ewallet/lib/ewallet/exchange/exchange.ex
Issue/Task Number: #518
closes #518
This PR always preloads tokens for the exchange pair when calling `/transaction.calculate`.
- Add a test to ensure the exchange pair tokens are properly preloaded
- Add the preloading of the exchange pair tokens
> Always preload tokens in exchange pair when doing /transaction.calculate

- apps/admin_api/test/support/conn_case.ex
- apps/ewallet/lib/ewallet/web/filters/match_all_query.ex
- apps/ewallet/lib/ewallet/web/filters/match_any_query.ex
- apps/ewallet/lib/ewallet/web/filters/match_parser.ex
- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/web/filters/match_all_query_test.exs
- apps/ewallet/test/ewallet/web/filters/match_any_query_test.exs
Issue/Task Number: #531
Closes #531
This adds support for nil value to `match_any` and `match_all` filtering
- Adds supports for nil value filtering
- Add proper error handling when filtering certain types of values is not supported
This is simple addition to MatchAnyQuery and MatchAllQuery to support `nil` value comparison, which is required by Ecto to use `is_nil/1` and not `== nil`
Try requesting with `match_all`, `match_any` with nil values
No changes to the API specs or DB schemas.
> Supports nil value filtering

- apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
Issue/Task Number: #537 
Closes #537 
This PR fixes the error 500 when filtering on `/api/admin/account.get_members`.
- Add handling for `{:error, :not_allowed, field}` in `AccountMembershipController`
- Converts top level fields to query under `membership.user`
- Added handling for `{:error, :not_allowed, field}` which is handled in other controllers
- Note that before converting filter fields from `field: email` to `field: user.email`, there's an extra check to make sure the fields are allowed by the `UserOverlay`
Example:
```sh
curl 10.5.10.10:4000/api/admin/account.get_members \
-H "Authorization: OMGAdmin <truncated>" \
-d '{
"id": "acc_01cwtpfkzkfdwb795aw5gmqzzv",
"match_all": [
{
"field": "id", …
```
> Fix /api/admin/account.get_members returning error 500 when filtering

- apps/activity_logger/priv/repo/migrations/20180907173648_add_audit.exs
- apps/activity_logger/priv/repo/migrations/20181129045732_rename_audit_to_activity_log.exs
Issue/Task Number: 594
Closes #594 
This PR fixes a migration related to the activity log PR that dropped an inexistent index.
> Fix migration index issue

- apps/ewallet/lib/ewallet/web/url_validator.ex
- apps/ewallet/test/ewallet/web/url_validator_test.exs
Issue/Task Number: #583
Closes #583 
This PR imposes a stricter redirect URL prefixes to prevent bypassing the checks with a domain name that contains the whole prefix.
- Updated `EWallet.Web.UrlValidator.allowed_redirect_url?/1` to add trailing slashes to both the given url and the allowed prefixes before the comparison.
- Add more tests with values as suggested by @jpopxfile
- `String.start_with/2` is used instead of regex as it should be more performant.
- Also the trailing slashes are added during the comparison instead of when the values are saved to the database. This should be safer as this makes the check independent of the functions that save the settings to the database.
Set `redirect_url_prefixes` settings to "http://example.com". Then try reset password with `redirect_url: …
> Stricter Redirect URL prefixes comparison

- apps/utils/lib/errors/invalid_date_format_error.ex
- apps/utils/lib/helpers/date_formatter.ex
- apps/utils/test/utils/helpers/date_formatter_test.exs
Issue/Task Number: #634
Closes #634 
This PR moves `EWallet.Errors.InvalidDateFormatError` to `Utils.Errors.InvalidDateFormatError`
- Move `EWallet.Errors.InvalidDateFormatError` to `Utils.Errors.InvalidDateFormatError`
- Update `Utils.Helpers.DateFormatter` accordingly
As most of the logic using `InvalidDateFormatError` has been moved to a more generic/decoupled `Utils` subapp, it makes sense to move the generic `InvalidDateFormatError` there as well.
Future references to `InvalidDateFormatError` should be `Utils.Errors.InvalidDateFormatError`.
No changes to the DB schema or API specs
> Move InvalidDateFormatError from EWallet.Errors to Utils.Errors

- .circleci/config.yml
- Makefile
- mix.exs
Issue/Task Number: #663
Run Dialyzer as part of the build process in order to ensure code are properly written.
- Cleanup build steps to use a shared workspace instead of cache
- Add Dialyzer step
You will probably see `dialyze` step failing in all PRs until everything is fixed.
> Add Dialyzer in build steps

- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/admin_api/priv/swagger/admin/request_bodies.yaml
Issue/Task Number: 635
Closes #635 
This PR adds the missing `redirect_url` param to the `me.update_email` open api endpoint.
> Add missing `redirect_url` param for `me.update_email` doc endpoint

- apps/admin_panel/assets/src/omg-page-configuration/index.js
Sometimes when saving gcs key you would insterted a newline `\r \n` and that will breaks the json validation. This PR fixes it.
- Fix configuration json validation.
- Remove some cases that disable the save config button.
Try to update gcs with json key and save it.
> Fix json validation for configuration

- apps/admin_api/lib/admin_api/v1/error_handler.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/update_email_controller_test.exs
- apps/ewallet/lib/ewallet/gates/update_email_gate.ex
- apps/ewallet_db/lib/ewallet_db/update_email_request.ex
- apps/ewallet_db/test/ewallet_db/update_email_request_test.exs
Issue/Task Number: #636 
Closes #636 
This PR fixes the error 500 when providing the email update endpoint with an invalid format email.
- Updated `EWalletDB.UpdateEmailRequest.generate/2`
- Added a test to cover this fix to `EWalletDB.UpdateEmailRequest` and `AdminAPI.V1.SelfController`
The fix is done by changing `EWalletDB.UpdateEmailRequest.generate/2` to consistently return either `{:ok, %EWalletDB.UpdateEmailRequest{}}` or `{:error, %Ecto.Changeset{}}`, instead of hard-pattern matching to `{:ok, _}`.
The following command should return a proper error response:
```sh
curl 10.5.10.10:4000/api/admin/me.update_email \
-H "Authorization: OMGAdmin <redacted>" \
-d '{
"email": "not an email", …
```
> Fix error 500 when updating an email with an invalid email format

- apps/admin_api/priv/swagger/user/request_bodies.yaml
- apps/local_ledger/test/local_ledger/transaction_test.exs
Issue/Task Number: #652
Closes #652
This PR attempts to fix a random test failure which seems to result from the race condition between two transactions in the same test.
- Updated a `LocalLedger.Transaction.insert/2` test to generate many more transactions within a short timeframe instead of two.
- Used `Task.async/1` with `Task.yield_many/2` instead of `Task.start_link/1` and many `ExUnit.Assertions.assert_receive/3`
- Generated 200 transactions within 0 - 100ms to better simulate simultaneous transactions
- With `Task.async/1` and `Task.yield_many/2` we can handle a lot of spawned tasks in one go, which would be very difficult with `Task.start_link/1` and `assert_receive/3`
Run `mix test` should return with all passing tests.
No changes to the DB schema or API specs.
> Fix a race condition while testing for simultaneous transfers on an insufficient fund

- apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/api_key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/api_key_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/api_key.ex
- apps/ewallet_db/lib/ewallet_db/key.ex
- apps/ewallet_db/test/ewallet_db/api_key_test.exs
Issue/Task Number: #655 
Closes #655
This PR excludes soft-deleted API keys from `/api_key.all`
- Add `APIKey.query_all/0` for generating a default APIKey query with soft delete excluded.
- Update APIKeyController to use the new `APIKey.query_all/0` instead of `APIKey` directly.
- Bonus: Add tests for /access_key.all
I created a new `APIKey.query_all/0` instead of adding `exclude_deleted/0` to the controller so that we don't need to add `exclude_deleted/0` all over the codebase.
Make a request to `/api_key.all` should return only API keys that have not been soft deleted.
No changes to the DB schema or API specs.
> Exclude soft-deleted API keys from /api_key.all

- apps/ewallet/lib/ewallet/release_tasks.ex
- docker-gen.sh
- rel/commands/config.sh
- rel/commands/initdb.sh
- rel/commands/seed.sh
- rootfs/entrypoint
- update-versions.sh
Issue/Task Number: #664 
Refactor `bin/ewallet config` command to accept shell quoting so that we could pass key and value with space in it (for example, Google Cloud JSON configuration). Note that this require proper shell quoting/escaping:
```
$ bin/ewallet config key "foo bar baz"
```
Will save `foo bar baz` to `key`. If explicit quote string is needed, you will need to use either:
```
$ bin/ewallet config key "\"foo bar baz\""
$ bin/ewallet config key '"foo bar baz"'
```
Which will save `"foo bar baz"` (with quote) to the `key`. Additionally, having space in key is supported in the same way as value although we do not have (or should have) any configuration key with space in it:
```
$ bin/ewallet config "just because you can" "doesn't mean you should"
```
Will save `doesn't mean you …
> Refactor config command to prevent double-argv parsing

- apps/admin_api/lib/admin_api/v1/controllers/account_wallet_controller.ex
- apps/ewallet_config/lib/ewallet_config/setting.ex
- apps/ewallet_config/priv/repo/seeds_settings/00_setting.exs
- apps/ewallet_config/test/ewallet_config/setting_test.exs
- apps/local_ledger/lib/local_ledger/application.ex
Issue/Task Number: 727
Closes #727 
There was some small issues with the settings, this PR fixes them.
- Add missing originator when the seed is updating the position
- Fix a bug where the value was lost when the position changes
- Fix a crash when changing the position of a setting with a secret value
- Set the correct application to `local_ledger` when loading the settings for the local ledger
The `cast_value(attrs, _)` function in the `Setting` module now returns the given unchanged attributes when there is no `value` provided in the attributes instead of setting the value to `nil`.
Running `mix seed` with updated setting position will now work.
N/A
> Fix settings

- rel/commands/config.sh
- rel/commands/initdb.sh
- rel/commands/seed.sh
Fix error reporting in `bin/ewallet` maintenance commands due to `bin/ewallet` script setting `set -e` which make `getopt` exit immediately when given an invalid argument (because we use inredirect checks via `$? != 0` to print help).
> Fix error reporting in commands.

- rel/commands/config.sh
- rel/commands/initdb.sh
- rel/commands/seed.sh
The `-* )` matching added in previous commit to (re-)handle argument error is now causing all commands to fail due to how we use `getopt` always result in having `--` for a positional argument, which happens to match `-*` and fail.
> Fix regressed bin/ewallet command due to -* matching

- apps/activity_logger/mix.exs
- apps/admin_api/mix.exs
- apps/admin_panel/mix.exs
- apps/ewallet/config/config.exs
- apps/ewallet/mix.exs
- apps/ewallet_api/mix.exs
- apps/ewallet_config/mix.exs
- apps/ewallet_db/mix.exs
- apps/load_tester/mix.exs
- apps/local_ledger/mix.exs
- apps/local_ledger_db/mix.exs
- apps/url_dispatcher/mix.exs
- apps/utils/mix.exs
Issue/Task Number: #740 
Closes #740 
This PR bumps up the version to `pre.2` (which I didn't do for `pre.1` 🙏).
- Update all Mixfile's version to `1.1.0-pre.2`
N/A
N/A
None
> Bump version to v1.1.0-pre.2

- README.md
Issue/Task Number: #744 
Closes #744
This fixes the curl commands in the `README.md` downloading files and saving with the name `-sSL`.
- Update curl commands in the `README.md` from `-o` to `-O`
N/A
Try the commands in the `README.md` again.
No changes to the API specs or DB schema.
> Fix documentation downloading scripts with the wrong file name

- .circleci/config.yml
Closes #742 
Currently tags are not getting built due to tags filter wasn’t being included in the branch filter for non-tag specific steps. This commit fixes that by make sure all tags are matched in non-tag specific steps.
> Fix tags building on Circle CI

- .circleci/config.yml
Issue/Task Number: #489
Required by #489
This PR pins the `v1.1` branch to `omisegoimages/ewallet-builder:v1.1` so that `master` branch can continue with `omisegoimages/ewallet-builder:stable` with an upgraded version of Elixir and etc.
- Pin `.circleci/config.yml` to `omisegoimages/ewallet-builder:v1.1`
None.
CircleCI-related only. And CircleCI should pick up this change automatically.
> Pin v1.1.x to ewallet-builder:v1.1

- apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/account_wallet_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/admin_user_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/role_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
- apps/admin_api/lib/admin_api/v1/controllers/user_auth_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_wallet_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_user_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/category_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/role_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_auth_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/admin_user_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/category_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/role_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/provider_auth/user_auth_controller_test.exs
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Issue/Task Number: #755 
Closes #755
This PR adds input handling for when `id` is not provided to various `/*.get` endpoints.
⚠️ **This PR add/edit the controller tests. This will require migrating these tests manually to the unified controller tests on master branch.**
- Add a `handle_error(conn, :missing_id)` or `handle_error(conn, :invalid_parameter, _)` to missing controller fallbacks.
Some older code seems to be missing a fallback for when `id` is not provided.
Note that there are still some inconsistency in how error messages are returned. Some endpoints would return simply `"Invalid parameter provided."`, while some others would return ``"Invalid parameter provided. `id` is required."``
But these inconsistencies are a cosmetic issue, since providers should not be parsing the …
> Fix various `/*.get` endpoints returning error 500 when not provided with `id`

- .circleci/config.yml
This PR fixes the circleci config referring to `ewallet-builder:stable` which is now running Elixir 1.8 image.
- Updated circleci config to use `ewallet-builder:v1.1`
Downgrading to `ewallet-builder:stable` to pin ewallet v1.1 branch to `ewallet-builder:v1.1` for good.
N/A
CircleCI only.
> Fix ewallet-builder tag on v1.1

- apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/account_wallet_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/admin_user_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/category_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/exchange_pair_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/role_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/transaction_consumption_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/transaction_request_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/user_auth_controller_test.exs
Issue/Task Number: 784
Closes #784 
This PR fixes some controller tests that was merged without using the new `test_with_auths` macro.
- Use `test_with_auths` where required
N/A
Run tests
N/A
> Fix wrongly merged controller tests

- .circleci/config.yml
- docker-gen.sh
Closes #787 
* Fixes stable tag detection
* Fixes tag detection for a version branch
* Fixes a missing ssh-keyscan during ls-remote
> Fix Docker push

- docker-gen.sh
Issue/Task Number: #775 
Requires #788
Updates docker-gen.sh to point to `omisego/ewallet:stable` now that v1.1.0 is the new stable.
⚠️ **Need to wait for the latest stable build to appear on [omisego/ewallet dockerhub](https://hub.docker.com/r/omisego/ewallet/tags) before merging.**
Updated `docker-gen.sh` to generate override that points to the stable docker tag.
N/A
N/A
N/A
> Update docker-gen.sh to use omisego/ewallet:stable after v1.1.0 release

- apps/ewallet_config/lib/ewallet_config/config.ex
- apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
Fix an issue where Goth fail to load credentials on application start due to Goth app has already been started and env never got populated there.
> Always restart Goth on settings load

- apps/admin_panel/assets/src/omg-invite-form/index.js
Issue/Task Number: - 
Unfortunately from some refactoring, the invite error handling breaks. This PR fixes it.
- Fix error handling.
Due to factoring, we changed how data returns from action. when success it will return `data` if not it will return a error as `error` object so we handle it accordingly.
Try inviting someone in.
We probably need to deploy a new stable version for this hot fix.
> Hotfix invite page broken

- apps/ewallet_api/config/prod.exs
- docs/setup/advanced/clustering.md
- rootfs/entrypoint
Closes #791 
We're no longer using `NODE_NAME` to set the name of an application for clustering (since in `vm.args` we now use a release name, which is "ewallet") so this PR remove all mentions of NODE_NAME and fix potential clustering but if NODE_NAME were happened to be set.
> Remove ability to configure NODE_NAME

- apps/ewallet_config/lib/ewallet_config/config.ex
- apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
- apps/ewallet_config/lib/ewallet_config/setting_loader.ex
Issue/Task Number: #795 
Closes #795 
Fixes settings loader not waiting for all settings to be refreshed before the specific loaders begin.
This causes the file adapter settings loader to use stale values for `gcs_*` and `aws_*` settings.
- Reverted #793 as that did not fix the issue
- Separated settings value loading and the specific loader loop so that settings are always fully populated first.
This is a bug introduced by #777 where the way specific loaders get triggered was changed. The specific loaders were moved into the same loop as settings loader and thus means that it gets triggered before all its dependent settings were populated. For example:
**Before #777:**
```elixir
config :ewallet_db,
settings: [
:base_url,
:min_password_length,
:file_storage_adapter,
:aws_bucket, …
```
> Fix settings being loaded before all settings are refreshed.

- apps/admin_api/config/config.exs
__This shouldn't be merged into v1.1.__
Issue/Task Number: #801 
closes #801
Not having the file storage settings in the Admin API was initializing them at `nil`, breaking the boot for GCS.
> Fix Goth strange behavior

- Makefile
* Switch to `omisegoimages/ewallet-builder:v1.1` image for builder.
* Make `make docker-push` makes.
-----
tl;dr you can now do this
```
make docker-push IMAGE_NAME=omisego/ewallet:dev-$(git rev-parse --short HEAD)
```
To build product image and push to Docker Hub (given that you’re logged in) as `dev-<shortref>`.
> Fix building in v1.1 due to stable image change

- apps/admin_api/test/admin_api/v1/controllers/configuration_controller_test.exs
- apps/ewallet_config/config/config.exs
- apps/ewallet_config/lib/ewallet_config/setting_validator.ex
- apps/ewallet_config/priv/repo/reporters/seeds_settings.exs
Issue/Task Number: #661
Closes #661
This PR prevents the following setting fields to be updated as `nil` or negative integer:
- `max_per_page`
- `min_password_length`
- `forget_password_request_lifetime`
- `balance_caching_reset_frequency`
- Change the following settings from `integer` to `unsigned-integer`
- `max_per_page`
- `min_password_length`
- `forget_password_request_lifetime`
- `balance_caching_reset_frequency`
> Improve configuration validation

- apps/ewallet/lib/ewallet/web/sort_parser.ex
This is a potential security issue if incoming `field` is not validated and you create new atoms on the spot. You can test this with the bellow test and observe how :erlang.system_info(:atom_count) is getting bigger. 
> Atoms are not garbage-collected. Once an atom is created, it is never removed. The emulator terminates if the limit for the number of atoms (1,048,576 by default) is reached.
- Map the incoming string with an existing atom from the table, throw ArgumentError if the atom doesn't exist
The implementation presupposes that all atoms from `allowed_fields` are already loaded in the release VM.
```
@tag timeout: 100_000_000
test "can sort a field by descending order" do
prepare_test_accounts()
master_account = Account.get_master_account()
attrs = %{"sort_by" => …
```
> prevent creating new atoms from external sources

- apps/ewallet_db/lib/ewallet_db/application.ex
- apps/ewallet_db/lib/ewallet_db/user_query.ex
- apps/local_ledger/lib/local_ledger.ex
- apps/local_ledger_db/lib/local_ledger_db/wallet.ex
Issue/Task Number: #610
This PR contains the small typo & deprecation fixes carried over from the now-closed #806.
- Typo fixes from renamings long time ago.
- Fix deprecated Ecto join without specifying `on:`
N/A
N/A
No changes to DB schema or API specs.
> Typo & deprecation fixes in EWalletDB and LocalLedgerDB namespaces

- apps/ewallet/test/ewallet/web/orchestrator_test.exs
Issue/Task Number: #843
Closes #843
This PR fixes random failure tests on:
- test/ewallet/web/orchestrator_test.exs:133
- test/ewallet/web/orchestrator_test.exs:175
- Added `sort_by: inserted_at`
> Fix failed new pagination tests

- apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/admin_api/priv/swagger/swagger.yaml
- apps/admin_api/priv/swagger/token/paths.yaml
- apps/admin_api/priv/swagger/token/request_bodies.yaml
- apps/admin_api/priv/swagger/token/response_schemas.yaml
- apps/admin_api/test/admin_api/v1/controllers/token_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/wallet_controller_test.exs
- apps/admin_api/test/admin_api/v1/views/token_view_test.exs
- apps/ewallet/lib/ewallet/web/v1/serializers/token_serializer.ex
- apps/ewallet/priv/swagger/token/schemas.yaml
- apps/ewallet/test/ewallet/web/v1/serializers/token_serializer_test.exs
- apps/ewallet_api/priv/spec.json
- apps/ewallet_api/priv/spec.yaml
- apps/ewallet_api/test/ewallet_api/v1/controllers/self_controller_test.exs
- apps/ewallet_db/lib/ewallet_db/token.ex
- apps/ewallet_db/priv/repo/migrations/20190301125055_add_avatar_to_tokens.exs
Issue/Task Number: #816
Closes #816
Requires #730 
This PR implemented an endpoint `token.upload_avatar` for providing a way to upload token's avatar
- Added an endpoint `token.upload_avatar` to router
- Added field `avatar` to schema.
- Added `AddAvatarToTokens` migration script.
Everything is the same to `account.upload_avatar`.
Try uploading an avatar with Postman or something.
`token.upload_avatar`
{
id: "tok_BTC_1234",
avatar: <binary>
}
Run `ecto.migrate` to add `avatar` field to `token` table.
> Add token avatar

- Makefile
- apps/status/.gitignore
- apps/status/README.md
- apps/status/config/config.exs
- apps/status/config/dev.exs
- apps/status/config/prod.exs
- apps/status/config/test.exs
- apps/status/lib/status.ex
- apps/status/lib/status/metric/recorder.ex
- apps/status/mix.exs
- apps/status/test/test_helper.exs
- apps/utils/lib/helpers/normalize.ex
- apps/utils/test/utils/helpers/normalize_test.exs
- docker-compose.yml
- rel/config.exs
AppSignal VM monitoring umbrella app. 
- Added a new umbrella application.
Decided for a separate umbrella application because it doesn't fit anywhere else.
It's enabled currently in the configuration, a deployment should (after setting up a custom dashboard) start sending the data to AppSignal backend.
AppSignal frontend configuration:
```
-
title: 'VM dashboard'
graphs:
-
title: 'VM atom over time'
kind: gauge
format: number
draw_null_as_zero: true
fields:
- erlang_system_info_atom_count
tags:
node: '*'
-
title: 'ETS count'
kind: gauge
draw_null_as_zero: false
fields:
- erlang_ets_count
tags:
node: '*'
-
title: 'IO Input KB'
kind: gauge
draw_null_as_zero: false
fields:
- erlang_io_input_kb
tags:
node: '*'
-
title: 'IO Output KB'
kind: gauge
format: number …
```
> feature: gather VM metrics and forward to AppSignal

- apps/ewallet/lib/ewallet/cli.ex
- apps/utils/lib/helpers/normalize.ex
Issue/Task Number: #851 
Closes #851
Add a `to_boolean/2` function to the `Normalize` module to make it possible for callers to specify a default value. Should only be used when having a default can be considered safe.
> Fix normalizer to make our lives easier

- .circleci/ci_e2e.sh
- .circleci/config.yml
- Makefile
Closes #732 
* Enables end-to-end testing in all branches
* Use `ENV_*` in `Makefile`
* Use `merge-base --fork-point` to detect a branch point to run E2E 
Result of these changes is that now branch based of `v1.2` will now run `v1.2` E2E instead of `master`.
> Enable E2E in all branches

- apps/activity_logger/config/config.exs
- apps/activity_logger/config/dev.exs
- apps/activity_logger/config/prod.exs
- apps/activity_logger/config/test.exs
- apps/activity_logger/mix.exs
- apps/db/lib/db/shared_connection_pool.ex
- apps/db/mix.exs
- apps/ewallet_config/config/config.exs
- apps/ewallet_config/config/dev.exs
- apps/ewallet_config/config/prod.exs
- apps/ewallet_config/config/test.exs
- apps/ewallet_config/mix.exs
- apps/ewallet_db/config/config.exs
- apps/ewallet_db/config/dev.exs
- apps/ewallet_db/config/prod.exs
- apps/ewallet_db/config/test.exs
- apps/ewallet_db/mix.exs
- apps/local_ledger_db/config/config.exs
- apps/local_ledger_db/config/dev.exs
- apps/local_ledger_db/config/prod.exs
- apps/local_ledger_db/config/test.exs
- apps/local_ledger_db/mix.exs
- docs/setup/advanced/env.md
Issue/Task Number: #327
Closes #327 
This PR implements `DB.SharedConnectionPool` to let repos that connect to the same database reuse the same connection pool, so we don't max out DB connections limit. Then exposes the pool for `ewallet` and `local_ledger` databases via ENV vars.
- Implemented `DB.SharedConnectionPool`
- Configure `ActivityLogger.Repo`, `EWalletConfig.Repo`, `EWalletDB.Repo` to use `DB.SharedConnectionPool` with `shared_pool_id: :ewallet`
- Configure `LocalLedgerDB.Repo` to use `DB.SharedConnectionPool` with `shared_pool_id: :local_ledger`
- Move common repo configs such as `:adapter` and `:migration_timestamps` into the main config files.
Currently each repo has its own independent connection pools. With the default `pool_size: 10`, this means `ActivityLogger.Repo`, …
> Allow DB connection pool sharing between repos

- apps/ewallet/lib/ewallet/web/filters/match_all_query.ex
- apps/ewallet/lib/ewallet/web/filters/match_any_query.ex
- apps/ewallet/lib/ewallet/web/filters/match_parser.ex
- apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
Closes #783
Queries are no longer limited by 5-associations.
The issue description suggested using named bindings but I found that using the existing Dynamic Queries with dynamic positioning to be better. Named bindings required creating compile-time atoms for every association within the schema in order to work. This added unnecessary complexity.
Implementation outline:
- do_filter_assoc() was generalized in MatchAllQuery and MatchAnyQuery
- checks for association limit was removed from MatchParser; 'position' variable adjusted.
- Added test case march_parser_tests.ex to check for 6-associations; also removed redundant test for 5-association limit
`{schema, position}` tuple used to bind the dynamic queries is an internal implementation of Ecto Queries. A …
> Remove 5-association limit from MatchParser #783

- apps/admin_api/test/admin_api/v1/controllers/wallet_controller_test.exs
Issue/Task Number: #831 
Closes #831
This PR fixes a random test error in WalletControllerTest due to indeterministic wallet balance order.
- Fixed a test in WalletControllerTest by asserting for specific values than the entire response.
N/A
`mix test` should not randomly fail as in #831.
No changes to API specs nor DB schema
> Fix a random test error in WalletControllerTest

- apps/ewallet/lib/ewallet/release_tasks/config_migration.ex
- apps/ewallet_config/lib/ewallet_config/setting.ex
Issue/Task Number: #798
Closes #798 
This PR skips migration of a specific settings if the settings value has not been changed.
This helps remove unnecessary database writes and activity logs caused by unchanged settings updates.
- Updated `EWallet.ReleaseTasks.ConfigMigration` to skip updating if a settings value is unchanged.
The `Settings` and `StoredSettings` is pretty complicated and adds a lot of changes to the changeset. Since this settings migration command mainly takes ENV values and saves to database, this PR skips unnecessary DB updates by checking whether the settings value changed. Only if it changed then it proceeds with the update.
Running this command the first time:
```shell
BASE_URL=http://localhost mix omg.config -m -y
```
Would result in:
```shell
Migrating the …
```
> Skip settings migration if the settings value has not been changed

- apps/ewallet/lib/ewallet/web/filters/match_all_query.ex
- apps/ewallet/lib/ewallet/web/filters/match_any_query.ex
- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/web/filters/match_all_query_test.exs
- apps/ewallet/test/ewallet/web/filters/match_any_query_test.exs
- apps/ewallet/test/ewallet/web/v1/error_handler_test.exs
Issue/Task Number: #814
Closes #814
This PR fixes the internal server error returned when providing a filter with a missing parameter.
- Updated `EWallet.Web.V1.ErrorHandler.template_replace/3` to stringify non-strings before attempting to build the error response.
Changing `EWallet.Web.V1.ErrorHandler.template_replace/3` to support non-string template data should be generic enough that passing other kinds of non-string data to the template in the future should work (as long as [Kernel.inspect/2](https://hexdocs.pm/elixir/Kernel.html#inspect/2) can handle it).
```shell
curl 'http://localhost:4000/api/admin/activity_log.all' \
-H 'Accept: application/vnd.omisego.v1+json' \
-H 'Authorization: OMGAdmin <redacted>' \
-H 'Content-Type: application/json;charset=UTF-8' \
--data-binary '
{ …
```
> Fix internal server error on missing filter params

- apps/admin_api/lib/admin_api/application.ex
- apps/admin_api/lib/admin_api/endpoint.ex
- apps/ewallet/config/config.exs
- apps/ewallet/lib/ewallet/web/config.ex
- apps/ewallet/test/ewallet/web/config_test.exs
- apps/ewallet_api/lib/ewallet_api/application.ex
- apps/ewallet_api/lib/ewallet_api/endpoint.ex
Issue/Task Number: 866
Closes #866 
This PR is an attempt to fix the currently broken CORS plug.
The previous configuration was not working properly because the configuration was set in application variables after the plug was initialized.
This PR moves the plug configuration setup at the `endpoint` level.
- Configure the plug at the `endpoint` level
- Refactor plug config
As the plug was not properly working until now, it was accepting all origins by default.
After this PR gets merged a proper configuration will be required.
> Fix cors config

- mix.lock
Issue/Task Number: 899
Closes #899 
This PR updates tzdata to version `0.5.20` in order to implement the fix for [this issue](https://github.com/lau/tzdata/issues/79)
- Bump version number
> Bump tzdata version

- apps/ewallet/lib/ewallet/release_tasks/config.ex
- apps/ewallet/lib/ewallet/release_tasks/config_migration.ex
- apps/ewallet_config/lib/ewallet_config/config.ex
- apps/utils/lib/helpers/normalize.ex
- apps/utils/test/utils/helpers/normalize_test.exs
Issue/Task Number: #804
Closes #804
This PR normalizes an ENV value to its respective settings' type before attempting to update into settings.
- Add `Config.update_one/3` for convenience when wanting to update a single settings
- Add `Normalize.to_strings/1` to normalize a comma-separated string (as expected as ENV values) into a list of strings.
- Updated `EWallet.ReleaseTasks.Config` with ENV value normalization according to each setting's type
- Updated `EWallet.ReleaseTasks.ConfigMigration` with ENV value normalization according to each setting's type
Notice that there's duplicate normalization code in `ReleaseTasks.Config` and `ReleaseTasks.ConfigMigration`. I think this is very specific to normalizing ENV values, which is unlikely to be used anywhere else, so it's simpler to …
> Normalize ENV values before saving to settings

- apps/admin_api/test/admin_api/v1/controllers/account_membership_controller_test.exs
- apps/ewallet/lib/ewallet/web/inviter.ex
Issue/Task Number: #925
#925
This PR fixes a bug where wallets were generated when inviting admin users to the system.
- Add tests showing the bug
- Ensure `is_admin` is properly set when inserted admin users
> Admin users wallets wrongly generated

- apps/ewallet_db/lib/ewallet_db/global_role.ex
- apps/ewallet_db/lib/ewallet_db/role.ex
Issue/Task Number: #926 #927 
closes #926
closes #927 
This PR adds the missing permissions for exchange pairs and the ability for admin users to update themselves (including changing their avatar).
> Add missing permissions

- apps/admin_panel/assets/package-lock.json
- apps/admin_panel/assets/package.json
- apps/admin_panel/assets/src/clientApp/index.js
- apps/admin_panel/assets/src/clientApp/omg-client-reset-password/index.js
- apps/admin_panel/assets/src/config/index.js
- apps/admin_panel/assets/src/index.js
- apps/admin_panel/assets/src/services/apiService.js
- apps/admin_panel/assets/src/services/apiService.test.js
- apps/admin_panel/assets/src/services/clientService.js
- apps/admin_panel/assets/src/utils/device.js
- apps/admin_panel/assets/src/utils/headerGenerator.js
- apps/admin_panel/assets/src/utils/headerGenerator.test.js
- apps/admin_panel/assets/webpack/webpack.dev.config.js
- apps/admin_panel/assets/webpack/webpack.prod.config.js
Issue/Task Number: #908 
Handle reset password on client.
- Add reset password fallback to app waiting scene.
There are many possibility for this,
- if it is a mobile, and foward_url exist we try to open an app and give a scene to wait.
- if not show usual form.
try on mobile, and also opening an app.
> Handle client reset password

- apps/admin_panel/assets/src/omg-account/action.js
- apps/admin_panel/assets/src/omg-page-account-setting/index.js
- apps/admin_panel/assets/src/services/accountService.js
Issue/Task Number: [383](https://github.com/omisego/ewallet/issues/383)
Adds a select category field to account settings
send the selected category with the update account call
- "Create account" currently only supports selecting one category, so i did the same here
- Allows user to save no category by emptying field
- Dont allow user to click save unless category is selected from dropdown
> Update categories in account settings

- apps/ewallet_db/priv/repo/migrations/20181113055250_add_id_and_deleted_at_to_role.exs
Issue/Task Number: #956 
Closes #956
Remove erlang datetime to NaiveDateTime conversion since it's already converted in later Ecto versions used by eWallet v1.2
- Remove erlang date time to NaiveDateTime conversion from role migrationn
See overview.
After this PR is merged `mix ecto.migrate` should pass successfully.
No changes to DB schema or API specs.
> Remove erlang datetime -> NaiveDateTime conversion from role migration

- .circleci/config.yml
- Makefile
- docker-compose.yml
- docker-gen.sh
- update-versions.sh
Issue/Task Number: #945, #972
Run frontend linting (`npm run lint`) as part of the build process, as well as automatically update versions in `mix.exs` during build process. The version number will be either:
* Just the tag, for tagged commit e.g. `1.2.0-pre.0` for `v1.2.0-pre.0` tag, prefix `v` truncated
* Latest tag plus number of commits since last tag, and a hash e.g. `1.2.0-pre.0-18-g343a6c80`
The latter is generated using `git describe --tags`. SHA hash for the commit is after the `g` letter.
This commit also fixes #971 where config command fails due to `KEYCHAIN_SECRET_KEY` not properly getting configured during E2E.
> Frontend lint release version

- apps/admin_panel/assets/src/adminPanelApp/routes/index.js
- apps/admin_panel/assets/src/clientApp/index.js
- apps/admin_panel/assets/src/omg-alert/reducer.js
- apps/admin_panel/assets/src/omg-page-user-setting/index.js
- apps/admin_panel/assets/src/omg-page-verify-email/index.js
- apps/admin_panel/assets/src/omg-session/action.js
- apps/admin_panel/assets/src/omg-session/action.test.js
- apps/admin_panel/assets/src/omg-user-current/action.js
- apps/admin_panel/assets/src/omg-user-current/action.test.js
- apps/admin_panel/assets/src/omg-user-current/reducer.js
- apps/admin_panel/assets/src/services/adminService.js
- apps/admin_panel/assets/src/services/currentUserService.js
- apps/admin_panel/assets/src/services/sessionService.js
Issue/Task Number: [949](https://github.com/omisego/ewallet/issues/949)
- update admin email in myprofile page
- link in verify email takes you to a page that makes the verify call with button back to dashboard
- redirect url still has /api in route. but if i remove this from my config, i get the cors error again. @jarindr knows more?
- split avatar, password, email updates into their respective calls as previously avatar update was dependent on email update. api calls also updated
> Update admin email

- apps/ewallet/lib/ewallet/web/filters/match_parser.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
- apps/ewallet/test/ewallet/web/v1/error_handler_test.exs
Issue/Task Number: #975
Closes #975
Fixes the internal server error returned when the provided with an invalid `match_all`/`match_any` filter attributes.
- `MatchParser` rejects filter attributes that are invalid (i.e. not in a list).
- Updated `:missing_filter_param` error description to `"Invalid parameter provided. Expecting an array of filter parameters."` for clarity
Server was crashing because `Enum.reduce_while/3` could be enumerated both over a list or a map. Since the expected value is a list, but a map could easily be mistaken (using only 1 set of filter, passed that set without wrapping in a list), this will be caught now before being handled.
Did this instead of supporting a single filter without list to keep the API consistent.
Request:
```shell
curl -X POST …
```
> Fix unhandled error when match_all/match_any format is incorrect

- apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
- apps/admin_api/lib/admin_api/v1/router.ex
- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/admin_api/priv/swagger/api_key/paths.yaml
- apps/admin_api/priv/swagger/api_key/request_bodies.yaml
- apps/admin_api/priv/swagger/swagger.yaml
- apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
Issue/Task Number: #991 
Closes #991 
This PR adds the simple `api_key.get` endpoint.
> Add api_key.get endpoint

- apps/admin_api/lib/admin_api/v1/controllers/balance_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/balance_controller_test.exs
- apps/ewallet/lib/ewallet/web/paginators/start_after_paginator.ex
- apps/ewallet/test/ewallet/web/paginators/start_after_paginator_test.exs
Issue/Task Number: #985
Closes #985
This PR fixes the exception raised when a given `start_by` field is not in the allowed list in  `/api/admin/wallet.get_balances`.
- Handles `{:error, code, description}` tuple in `BalanceController`
- Fix exception thrown when an unrecognized field is given.
This 3-element error tuple was introduced in #719 and unfortunately `BalanceController` is the only controller that handles only 2-element error tuple. Already checked the rest of the controllers.
As described in #985
No changes to the API specs or DB schemas.
> Fix exception raised when the given `start_by` field is not allowed

- apps/admin_panel/assets/package-lock.json
- apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
- apps/admin_panel/assets/src/omg-exchange-rate-modal/createExchangeModal.js
- apps/admin_panel/assets/src/omg-page-account/index.js
- apps/admin_panel/assets/src/omg-page-activity-log/index.js
- apps/admin_panel/assets/src/omg-page-admins/index.js
- apps/admin_panel/assets/src/omg-page-consumption/index.js
- apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
- apps/admin_panel/assets/src/omg-page-members/index.js
- apps/admin_panel/assets/src/omg-page-token/index.js
- apps/admin_panel/assets/src/omg-page-transaction-request/index.js
- apps/admin_panel/assets/src/omg-page-transaction/index.js
- apps/admin_panel/assets/src/omg-page-users/index.js
- apps/admin_panel/assets/src/omg-page-wallets/index.js
- apps/admin_panel/assets/src/omg-uikit/input/index.js
- apps/admin_panel/assets/src/utils/formatter.js
- apps/admin_panel/assets/src/utils/formatter.test.js
Issue/Task Number: #980 
When creating rate, the amount is not passed correctly because it divided a string `x,xxx` / `y,yyy`.
- Fix rate dividing.
- Fix height and unused css for top navigation.
- Fix edit rate returning [Object]
Deploy as usual
> Fix rate exchange bug

- apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
- apps/admin_api/priv/spec.json
- apps/admin_api/priv/spec.yaml
- apps/admin_api/priv/swagger/exchange_pair/request_bodies.yaml
- apps/admin_api/test/admin_api/v1/controllers/exchange_pair_controller_test.exs
- apps/ewallet/lib/ewallet/gates/exchange_pair_gate.ex
- apps/ewallet/test/ewallet/gates/exchange_pair_gate_test.exs
Issue/Task Number: #996
Closes: #996
This PR add supports for exchange pair's creation and update by passing the rate as a string.
- Attempts to parse a string rate into float in `EWallet.ExchangePairGate`
This is a small update to the `ExchangePairGate` that tries to parse a string rate before doing the insert/update.
A caveat is that this uses `Float.parse/1` which means that there could be precision loss in the floating point returned. But since the DB is already storing the rate as a floating point, this does not introduce more precision loss than it already is. The precision loss is #998.
```shell
curl -X POST localhost:4000/api/admin/exchange_pair.create \
-H "Authorization: OMGAdmin <truncated>" \ …
```
> Supports passing exchange pair's rate as string

- apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
- apps/admin_api/test/admin_api/v1/controllers/transaction_controller_test.exs
- mix.exs
Issue/Task Number: #1022 
closes #1022 
This PR adds the proper parameter for the endpoint: `id` (instead of `user_id` and `provider_user_id` - those are still supported but `user_id` shouldn't be used anymore and isn't documented.
- Add a test
- Fix endpoint
> Fix /user.get_transactions wrong parameters

- apps/ewallet_api/lib/ewallet_api/v1/end_user_authenticator.ex
- apps/ewallet_api/test/ewallet_api/v1/controllers/auth_controller_test.exs
Issue/Task Number: #1025 
closes #1025
Check that the logged in user is not an admin in the `/user.login` client endpoint.
- Add a test to reflect the bug
- Fix the issue by preventing admins from logging in
> Prevent admin users from logging in through the client API

- apps/ewallet_db/priv/repo/reporters/seeds.exs
Issue/Task Number: #1037 
Closes #1037
Fixes admin panel's URL in seeding output
- Removed the extra `/admin` from the admin url building logic
String replaced.
`mix seed` should now inform the correct admin panel url
No changes to DB or API.
> Fix admin panel url in seeding output

- apps/admin_api/lib/admin_api/v1/auth/admin_user_auth.ex
- apps/admin_api/test/admin_api/v1/controllers/admin_user_controller_test.exs
- apps/admin_api/test/admin_api/v1/controllers/user_controller_test.exs
- apps/ewallet/lib/ewallet/auth/user_authenticator.ex
- apps/ewallet/test/ewallet/auth/user_auth_token_test.exs
- apps/ewallet_api/lib/ewallet_api/v1/auth/client_auth.ex
- apps/ewallet_api/test/ewallet_api/v1/auth/client_auth_test.exs
- apps/ewallet_api/test/ewallet_api/v1/plugs/client_auth_plug_test.exs
- apps/ewallet_config/config/config.exs
- apps/ewallet_db/config/config.exs
- apps/ewallet_db/lib/ewallet_db/auth_token.ex
- apps/ewallet_db/lib/ewallet_db/expirers/auth_expirer.ex
- apps/ewallet_db/lib/ewallet_db/pre_auth_token.ex
- apps/ewallet_db/priv/repo/migrations/20190426083108_add_expire_at_to_auth_tokens.exs
- apps/ewallet_db/priv/repo/migrations/20190426083132_add_expire_at_to_pre_auth_tokens.exs
- apps/ewallet_db/test/ewallet_db/auth_token_test.exs
- apps/ewallet_db/test/ewallet_db/expirers/auth_expirer_test.exs
- apps/ewallet_db/test/ewallet_db/pre_auth_token_test.exs
- apps/frontend/assets/src/adminPanelApp/routes/index.js
- apps/frontend/assets/src/omg-session/reducer.js
Issue/Task Number: #953 
Closes #953
This PR implements the authentication token expiration.
The default behavior of this feature is: the authentication token will never be expired unless the settings (:pre_auth_token_lifetime and :auth_token_lifetime) are set to the integer which more than zero.
- Added `expire_at` to `AuthToken` and `PreAuthToken`
- Added `:pre_auth_token_lifetime` in the setting to specify how long the `PreAuthToken` can be used.
- Added `:auth_token_lifetime` in the setting to specify how long the `AuthToken` can be used.
- Added an ability to expire either `PreAuthToken` or `AuthToken` or both.
> Note: `:pre_auth_token_lifetime` and `:auth_token_lifetime` can be positive integer or `0`. By set it to `0`, meaning that the `auth_token` or `pre_auth_token` will never be …
> Add auth token expiration

- apps/ewallet/lib/ewallet/web/filters/match_parser.ex
- apps/ewallet/lib/ewallet/web/orchestrator.ex
- apps/ewallet/lib/ewallet/web/v1/error_handler.ex
- apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
- apps/ewallet/test/ewallet/web/orchestrator_test.exs
Issue/Task Number: #1051
This PR fixes a specific case of filtering when an association name is given as the filter param without specifying the association's field.
- Add a guard so association filters do not get processed as a field.
Overlay filters could be in the form of:
```elixir
[
some_field: nil,
some_id: :uuid,
some_assoc: [:id, :name]
]
```
So when an association is given as a filter param without its dot-notated subfield, e.g. `field: "some_assoc"` instead of `field: "some_assoc.id"`, it treats `[:id, :name]` as a field type like `:uuid` instead of a list of associated subfields, and hence the internal server error.
An `is_list(type)` guard is added to catch the association and return `: missing_subfield` for further processing by the parser and orchestrator.
Try the request in …
> Fix internal server error when providing an association as the filter param

- README.md
Issue/Task Number: n/a
Cleaned up the language a bit with plural/singular clarification as well as a missing verb here and there.
- Readme.md grammar
> Fix some minor errors in README grammar

- apps/admin_api/test/admin_api/v1/controllers/transaction_consumption_controller_test.exs
- apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
- apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs
- apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
- apps/ewallet_db/lib/ewallet_db/transaction_request.ex
- apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Issue/Task Number: #1053 
Closes #1053 
This PR allows the transaction consumption with an expired transaction request with `expiration_reason = "expired_transaction_request"` to be confirmed
> ⚠️  Waiting branch 950-add-endpoint-cancel-transaction-request to be merged
> Minor fix transaction consumption confirmation

- apps/ewallet/lib/ewallet/web/v1/overlays/invite_overlay.ex
- apps/ewallet/lib/ewallet/web/v1/overlays/token_overlay.ex
- apps/ewallet/lib/ewallet/web/v1/overlays/transaction_consumption_overlay.ex
- apps/ewallet/lib/ewallet/web/v1/overlays/user_overlay.ex
Issue/Task Number: #1063 
Closes #1063
This PR adds more fields supported for advanced filtering as following:
- Added `created_at` and `wallet.address` to **TransactionConsumption**.
- Added `accounts.*`, `invite.*`, `wallet.*`, `auth_tokens.*`, `membership.*`, `roles.*` to **User**
- Added `account.*` to **Token**
- Added `user.*` to **Invite**
> Fix can't filter for some fields

- apps/ewallet/lib/ewallet/auth/backup_code_authenticator.ex
- apps/ewallet/lib/ewallet/auth/two_factor_authenticator.ex
- apps/ewallet/test/ewallet/auth/backup_code_authenticator_test.exs
- apps/ewallet/test/ewallet/auth/two_factor_authenticator_test.exs
- apps/ewallet_db/lib/ewallet_db/user_backup_code.ex
- apps/ewallet_db/test/ewallet_db/auth_token_test.exs
- apps/ewallet_db/test/ewallet_db/expirers/auth_expirer_test.exs
- apps/ewallet_db/test/ewallet_db/pre_auth_token_test.exs
- apps/ewallet_db/test/ewallet_db/user_backup_code_test.exs
Issue/Task Number: #1069 
Closes #1069
This PR improves backup code verification performance by replacing the hashing logic as follow:  
- From `Crypto.hash_password` to `Crypto.hash_secret`
- From `Crypto.verify_password` to `Crypto.verify_secret` 
The PR also move the backup code hashing logic from `EWallet.BackupCodeAuthenticator` to `EWalletDB.UserBackupCode` so it's closer to the source (fewer data passing steps).
> Improve backup code verification performance

- apps/ewallet/lib/ewallet/web/filters/match_parser.ex
- apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
Issue/Task Number: #1079 
Close #1079
This PR fixes the internal server error when filtering with both `match_all` and `match_any` with both containing nested fields.
- Added an offset to `MatchParser.join_assocs/2` so it offsets the new join position with any joins that happened before entering the function.
`MatchParser` relied on join position to correctly place its `where` conditions. Previously this position did not take into account any previous joins that have already happened and so it attempts to `where` on the incorrect join. 
This PR counts the number of existing joins and offset the new join position by that number.
Try another request with filtering, example in #1079
No changes to DB schema or API specs.
> Fix match_all & match_any combo failing on nested fields

- apps/frontend/assets/src/omg-alert/index.js
- apps/frontend/assets/src/omg-alert/reducer.js
Issue [1117](https://github.com/omisego/ewallet/issues/1117)
New flash message design -> https://gallery.io/projects/MCHbtQVoQ2HCZfyN0ITInFtb/files/MCEJu8Y2hyDSccxx6cKiHbSqjubRQ-UMc_Y
can now pass icon, duration, and action buttons to createAlertState in alerts reducer
`createAlertState('Blockchain disabled', 'warn', 'Link', 15000, [{ onClick: dosomething, text: 'Click Me' }])`
> New flash message

- apps/keychain/lib/keychain/wallet.ex
Issue/Task Number: 1125
Closes #1125 
This PR fixes the way private keys for the hot wallets are generated.
Previously, the byte size of the private key was randomly 31 instead of 32. 
Instead of using the `ExthCrypto.ECIES.ECDH. new_ecdh_keypair ` function, we directly use the erlang function and pass it the randomly generated private key.
> Fix private key generation

- docs/guides/README.md
Path was doc not docs in [Two-factor Authentication](/docs/guides/two_factor_authentication.md) and pointing to Page not found
> Fix broken link in readme

- apps/eth_blockchain/lib/eth_blockchain/application.ex
- apps/eth_blockchain/lib/eth_blockchain/blockchain_registry.ex
- apps/eth_blockchain/lib/eth_blockchain/nonce.ex
- apps/eth_blockchain/lib/eth_blockchain/nonce_registry.ex
- apps/eth_blockchain/lib/eth_blockchain/transaction.ex
- apps/eth_blockchain/test/eth_blockchain/blockchain_registry_test.exs
- apps/eth_blockchain/test/eth_blockchain/nonce_registry_test.exs
- apps/eth_blockchain/test/eth_blockchain/nonce_test.exs
- apps/eth_blockchain/test/support/dumb_adapter.ex
- apps/eth_geth_adapter/lib/eth_geth_adapter/transaction.ex
- apps/eth_geth_adapter/lib/eth_geth_adapter/worker.ex
Issue/Task Number: 1088
Closes #1088 
This PR adds a nonce handler that will give an incremented nonce for each new transaction from the same account. This allows an address to do more than 1 transaction per block.
- Add `EthBlockchain.Nonce` module
- Update `EthBlockchain.Transaction` to take nonce from the new module
> Add nonce handler

- .circleci/config.yml
Now with many members working on the repo, the slack notifications are getting a bit noisy. This PR limits failure notifications to main branches namely `master`, `v[0-9]+.*` and `eth_blockchain` (`eth_blockchain` can be removed once done).
- Update circleci's config for `notify_slack_failure` to notify only for main branches
N/A
N/A
N/A
> Notify failures to slack only for main branches

- .circleci/config.yml
Fix #1141.
- Updated circleci config
Had to use a less strict condition with `v[0-9]*` since case only supports globbing, not regex. 
N/A
N/A
> Fix notify slack case

- apps/ewallet/lib/ewallet/gates/transactions/blockchain_local_transaction_gate.ex
- apps/ewallet/lib/ewallet/gates/transactions/blockchain_transaction_gate.ex
- apps/ewallet/test/ewallet/gates/blockchain/blockchain_deposit_wallet_gate_test.exs
- apps/ewallet/test/ewallet/gates/transactions/blockchain_transaction_gate_test.exs
- apps/ewallet/test/ewallet/trackers/address_tracker_test.exs
- apps/ewallet_db/lib/ewallet_db/state_machines/transaction_state.ex
- apps/ewallet_db/test/ewallet_db/state_machines/transaction_state_test.exs
- apps/local_ledger/lib/local_ledger/cached_balance.ex
- apps/local_ledger/lib/local_ledger/entry.ex
- apps/local_ledger/lib/local_ledger/transaction.ex
- apps/local_ledger/test/local_ledger/cached_balance_test.exs
- apps/local_ledger/test/local_ledger/entry_test.exs
- apps/local_ledger/test/local_ledger/transaction_test.exs
- apps/local_ledger_db/lib/local_ledger_db/cached_balance.ex
- apps/local_ledger_db/lib/local_ledger_db/entry.ex
- apps/local_ledger_db/lib/local_ledger_db/transaction.ex
- apps/local_ledger_db/priv/repo/migrations/20190823080516_add_status_to_transaction.exs
- apps/local_ledger_db/test/local_ledger_db/cached_balance_test.exs
Issue/Task Number: #1086 
This PR adds the support for internal to external, in the fastest possible way. The code isn't super clean, let's be honest, but it works. 
- Allow the transfer from internal wallets to external addresses.
Add a new status to local ledger transactions, that's defaulting to `confirmed`. The eWallet can specify a transaction as being pending, which means it's included into the calculations, but can be turned into a failed transaction, which will not be counted.
> Supporting internal -> external transactions

- apps/keychain/lib/keychain/wallet.ex
- apps/keychain/test/keychain/wallet_test.exs
- apps/utils/lib/helpers/crypto.ex
- apps/utils/test/utils/helpers/crypto_test.exs
Crypto key generation could produce a private key that is 31 or 32 bytes long. This PR pads the key to 32 bytes so it can be base16-encoded properly.
- Added `Utils.Helpers.Crypto.pad_bytes/2`
- Updated `Keychain.Wallet.generate/0` to pad the private key binary before encoding and saving to database.
`:crypto.generate_key/3` sometimes generate a 31-byte long private key. A reproduction script is:
```elixir
for i <- 1..1000 do
{pub, priv} = :crypto.generate_key(:ecdh, :secp256k1, :crypto.strong_rand_bytes(32))
encoded_priv = Base.encode16(priv, case: :lower)
encoded_priv_length = String.length(encoded_priv)
if encoded_priv_length != 64 do
byte_size(priv) |> IO.inspect(label: "byte size")
encoded_priv |> byte_size() |> IO.inspect(label: "encoded byte size") …
```
> Pad private keys before encoding and storage

- apps/ewallet/lib/ewallet/cli.ex
- apps/ewallet/lib/ewallet/release_tasks/config.ex
- apps/ewallet/lib/ewallet/release_tasks/config_migration.ex
- apps/frontend/lib/frontend/application.ex
- apps/status/lib/status.ex
- apps/url_dispatcher/lib/url_dispatcher/application.ex
- apps/utils/lib/helpers/normalize.ex
- apps/utils/lib/helpers/path_resolver.ex
- apps/utils/test/utils/helpers/normalize_test.exs
Issue/Task Number: #894
Closes #894
This PR fixes the issue where passing a value that could not be converted to a boolean would throw an exception and stacktrace to the user.
- Converted `Utils.Helpers.Normalize.to_boolean/1` to return error tuple and moved the exception raising to `Utils.Helpers.Normalize.to_boolean!/1` instead.
- Converted `Utils.Helpers.Normalize.to_integer/1` to return error tuple and moved the exception raising to `Utils.Helpers.Normalize.to_integer!/1` instead.
Since there are both interfaces that are exposed to user and those that are part of application startup that uses this normalize function. The user-exposing parts are changed to use `to_boolean/1` and handle the error by transforming the error tuple to proper message for user.
The rest are used during …
> Fix passing boolean-incompatible value throwing error on `mix omg.config`

- apps/eth_blockchain/lib/eth_blockchain/transaction.ex
- apps/eth_blockchain/test/eth_blockchain/transaction_test.exs
- apps/eth_blockchain/test/support/dumb_tx_error_adapter.ex
- apps/eth_blockchain/test/support/eth_blockchain_case.ex
Issue/Task Number: #1166
This PR broadens the scope that nonce assignment should get reverted when the blockchain transaction returned an error.
- Updated `EthBlockchain.Transaction` to force-refresh the nonce for all blockchain transaction submission error.
There's already existing code to handle nonce reversal when a transaction submission errors, but it only covers nonce too low cases:
```elixir
{:error, :geth_error, [error_message: "nonce too low"]}
```
Another common error that should do nonce reversal is insufficient funds:
```elixir
{:error, :geth_error, [error_message: "insufficient funds for gas * price + value"]}
```
By wildcarding to `{:error, _, _}` we will cover both `:geth_error` and `:geth_communication_error` returned by `EthGethAdapter.ErrorHandler.handle_error/1`, which …
> Revert nonce if a blockchain transaction returned an error
