README.md

Issue/Task Number: T836
We have just open-sourced [Goban](https://github.com/omisego/goban). This PR adds the instruction to use Goban into eWallet repo.
- Updated readme to include "Quick installation with Goban"
Textual changes to the readme.
N/A
N/A

Add to readme: Installation with Goban

---

apps/admin_panel/lib/admin_panel/application.ex
apps/url_dispatcher/lib/mix/tasks/omg.server.ex

Issue/Task Number: T137
This PR allows starting the server with `--no-watch` flag that prevents webpack watch from running.
- Added an argument parser in `Mix.Task.Omg.Server` to parse for `--no-watch` flag. If the flag is found, it sets `:start_with_no_watch` config to `true`
- Updated `AdminPanel.Application` to look for `:start_with_no_watch` value. If set to true, it will not add `webpack --watch-stdin ...` as a worker, and hence the front end assets will not be watched for changes.
There are a few naming options for this flag. I decided to go for `--no-watch` instead of `--no-admin-panel` or `--backend`, etc. because it's still possible to do `yarn build` manually and the admin panel will still be served. This PR is supposed to disable the watch only.
The reason I needed to add a new …

`mix omg.server --no-watch` to disable webpack watch

---

apps/admin_panel/assets/src/pages/authenticated/transactions/list/tables.js

Issue/Task Number: `152-fix-admin-panel-transaction-list`
Fix transaction list has broken because the response structure has been changed.
- Update `transaction/list/tables.js` to follow this response structure.
```
{
"version": "1",
"success": true,
"data": {
"pagination": {
"per_page": 10,
"is_last_page": false,
"is_first_page": true,
"current_page": 1
},
"object": "list",
"data": [
{
"updated_at": "2018-03-14T10:42:21.982037Z",
"to": {
"object": "transaction_source",
"minted_token": {
"updated_at": "2018-03-14T09:42:17.267266Z",
"symbol": "OMG",
"subunit_to_unit": 10000,
"object": "minted_token",
"name": "OmiseGO",
"metadata": {},
"id": "OMG:20f18fe9-3354-4ef8-9853-226f633a4ef2",
"encrypted_metadata": {},
"created_at": "2018-03-14T09:42:17.267256Z"
},
"amount": 40,
"address": …
```

Fix transaction list has broken

---

apps/admin_api/config/config.exs
apps/admin_api/config/dev.exs
apps/admin_panel/config/config.exs
apps/admin_panel/config/dev.exs
apps/ewallet/config/config.exs
apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
apps/ewallet_api/config/config.exs
apps/ewallet_db/config/test.exs
apps/local_ledger_db/config/config.exs
apps/local_ledger_db/config/test.exs
config/prod.exs

Issue/Task Number: .
This PR unifies the logging logic in the containing application and gives a way to change the logging level with an ENV variable.
- Unify logging logic
- Add info logging when events are sent to channels

Remove logger from all config except containing app

---

apps/ewallet_db/lib/ewallet_db/minted_token.ex
apps/ewallet_db/test/ewallet_db/minted_token_test.exs

Issue/Task Number: T21
This PR adds two more validations to minted tokens: `subunit_to_unit` range check and `friendly_id` immutability.

Validate minted token subunit_to_unit and friendly_id

---

apps/admin_api/lib/admin_api/v1/error_handler.ex
apps/admin_api/lib/admin_api/versioned_router.ex
apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
apps/admin_api/test/admin_api/v1/error_handler_test.exs
apps/admin_api/test/admin_api/versioned_router_test.exs
apps/ewallet/lib/ewallet/web/api_docs/errors.html.eex
apps/ewallet/lib/ewallet/web/api_docs/errors.yaml.eex
apps/ewallet/lib/ewallet/web/v1/error_handler.ex
apps/ewallet/lib/ewallet/web/v1/serializers/websocket_response_serializer.ex
apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
apps/ewallet/test/ewallet/web/v1/serializers/websocket_response_serializer_test.exs
apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
apps/ewallet_api/lib/ewallet_api/versioned_router.ex
apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
apps/ewallet_api/test/ewallet_api/v1/controllers/user_controller_test.exs
apps/ewallet_api/test/ewallet_api/v1/error_handler_test.exs
apps/ewallet_api/test/ewallet_api/versioned_router_test.exs
apps/local_ledger/lib/local_ledger/entry.ex
apps/local_ledger/test/local_ledger/entry_test.exs

Issue/Task Number: T12
This PR refactors the error logic to be shared between the two APIs.
- Extract the shared logic (and refactor it) into a new ErrorHandler
- Keep the current error handlers in the APIs and delegate the calls to the shared ErrorHandler
- Give the possibility for shared errors as well as API specific ones.
- Works well with the current error listing
- The new error handler handle errors in a better and more unified way. There are four ways to use it (changeset, existing code, custom code and with template).
- A simple template system has been added to avoid adding new functions for each custom error description.

T12 - Top level errors

---

apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
apps/ewallet/lib/ewallet/web/v1/error_handler.ex
apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
apps/ewallet/lib/ewallet/web/v1/serializers/websocket_response_serializer.ex
apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
apps/ewallet/test/ewallet/web/v1/serializers/transaction_consumption_serializer_test.exs
apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
apps/ewallet/test/ewallet/web/v1/serializers/websocket_response_serializer_test.exs
apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
apps/ewallet_api/priv/spec.yaml
apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
apps/ewallet_db/lib/ewallet_db/transaction_request.ex
apps/ewallet_db/priv/repo/migrations/20180410032138_rename_consumption_timestamp_columns.exs
apps/ewallet_db/test/ewallet_db/transaction_consumption_test.exs
apps/ewallet_db/test/ewallet_db/transaction_request_test.exs

Issue/Task Number: T210
Describe what your Pull Request is about in a few sentences. This is a global description that should tell people what your PR is all about. Don't go too much into details here.
- Merge consumption approval/rejection event into one (`finalized`)
- Prevent approval of consumption if the request OR the consumption has expired.
- Prevent creation of a request with `allow_amount_override` set to `false` and a `nil` amount.
- Handle unauthorized amount override
- Merge consumption state machine and approval flow
- Double check expiration before checking validity
Most of the features seem there and everything should be working as expected. But I'm really feeling an actual refactor would really help since I've been adding quite a lot of stuff. Also, still can't figure out …

Update consumption event (again)

---

apps/admin_api/priv/spec.yaml

Fixed issue #183

---

docs/guides/transaction_request_flow.md
docs/websockets/ewallet_api.md

Issue/Task Number: T168
This PR adds some documentation about websockets and transaction requests.
- Add `docs/websockets/ewallet_api.md` which contains the list of channels and events
- Add `docs/guides/transaction_request_flow.md` which contains a quick overview of how transaction requests can be used.

Websocket and transaction request flow docs

---

apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs

Issue/Task Number: T284
Add `max_consumptions_per_user` in the params to create a request.

Fix max consumptions per user

---

Jenkinsfile

Update staging deploy configuration filename per internal Kubernetes configuration file cleanup.
- Change from `ewallet.yaml` to `deployment.yaml`
Nah
Nah
No

Update staging deploy configuration filename

---

apps/admin_api/priv/spec.yaml

Oops... Put some double quotes in the spec. somehow. Fixing it in this PR.

Fix double quotes in OpenAPI Spec

---

apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
apps/admin_api/lib/admin_api/v1/router.ex
apps/admin_api/priv/spec.yaml
apps/admin_api/test/admin_api/v1/controllers/self_controller_test.exs
apps/ewallet_db/lib/ewallet_db/user.ex
apps/ewallet_db/test/ewallet_db/user_test.exs

Issue/Task Number: 288
This PR adds the me.update endpoint to the admin API. It allows to update the currently logged in user.
- Add `me.update` to admin API

T288 update user

---

apps/ewallet_api/priv/spec.yaml

Issue/Task Number: T369
Add `formatted_id` to relevant endpoints in OpenAPI spec.

Add formatted_id to OpenAPI Spec

---

apps/admin_panel/assets/src/app/routes/index.js
apps/admin_panel/assets/src/omg-account-category/action.js
apps/admin_panel/assets/src/omg-account-category/categoriesProvider.js
apps/admin_panel/assets/src/omg-account-category/reducer.js
apps/admin_panel/assets/src/omg-account-category/selector.js
apps/admin_panel/assets/src/omg-alert/reducer.js
apps/admin_panel/assets/src/omg-api-keys/action.js
apps/admin_panel/assets/src/omg-create-account-modal/ChooseCategoryStage.js
apps/admin_panel/assets/src/omg-createNewPassword-form/index.js
apps/admin_panel/assets/src/omg-invite-form/index.js
apps/admin_panel/assets/src/omg-invite-modal/index.js
apps/admin_panel/assets/src/omg-invite/action.js
apps/admin_panel/assets/src/omg-invite/reducer.js
apps/admin_panel/assets/src/omg-page-account-setting/index.js
apps/admin_panel/assets/src/services/categoryService.js
apps/admin_panel/assets/src/services/settingService.js

Issue/Task Number: 380-invite-user
This PR enable the functionality for inviting user with email.
- Wire up invitation logic.
- Add invite page.
- Change validation logic, once everything settled I will refactor out the validation from all components.
- Add alert for invitation.
- since invite endpoint does not return the invited person, for now to get the newest data on page we will fetch the whole list of users again.
Go to setting menu, invite people by email and link that user to the admin panel.

380-invite-user

---

apps/ewallet_api/test/support/channel_case.ex

Issue/Task Number: T384
Switch Channel tests to shared sandbox mode.
- Shared mode for Ecto Sandbox

Enforce shared mode for channel tests

---

.github/CONTRIBUTING.md
README.md

Issue/Task Number: T396 & T400
Adds a list of commands that are required to be run successfully for a build to pass. Also replaces Rocket Chat with Gitter.
- Added required build commands:
- `mix format`
- `mix credo`
- `mix dialyzer`
- `mix test`
- Replaces all occurrences of Rocket Chat with Gitter
Now that we have more contributors to the project and more checks during the build, it's good to have a list of required commands in the readme.
We discussed in Gitter that an example hook would be nice. However I realized that we have multiple ways to setup the development environment for eWallet so I'm simply listing the required commands here.

Update README with build requirements & Gitter

---

apps/ewallet_db/priv/repo/seeds/01_api_key.exs
apps/ewallet_db/priv/repo/seeds/02_auth_token.exs
apps/ewallet_db/priv/repo/seeds/02_membership.exs
apps/ewallet_db/priv/repo/seeds_sample/00_account.exs
apps/ewallet_db/priv/repo/seeds_sample/00_api_key.exs
apps/ewallet_db/priv/repo/seeds_sample/00_key.exs
apps/ewallet_db/priv/repo/seeds_sample/00_token.exs
apps/ewallet_db/priv/repo/seeds_sample/01_auth_token.exs
apps/ewallet_db/priv/repo/seeds_sample/01_membership.exs
apps/ewallet_db/priv/repo/seeds_sample/02_category.exs

Issue/Task Number: 434
This PR fixes an issue in the seeds where we were still using the `Preloader.preload(...)` function
- Change `Preloader.preload(...)` to `Preloader.preload_one(...)`

Fix seeds preloader

---

apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
apps/admin_api/lib/admin_api/v1/router.ex
apps/admin_api/lib/admin_api/v1/views/exchange_pair_view.ex
apps/admin_api/priv/spec.yaml
apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
apps/admin_api/test/admin_api/v1/views/exchange_pair_view_test.exs
apps/ewallet/lib/ewallet/fetchers/uuid_fetcher.ex
apps/ewallet/lib/ewallet/policies/exchange_pair_policy.ex
apps/ewallet/lib/ewallet/web/v1/error_handler.ex
apps/ewallet/lib/ewallet/web/v1/serializers/exchange_pair_serializer.ex
apps/ewallet/test/ewallet/web/v1/serializers/exchange_pair_serializer_test.exs
apps/ewallet_db/lib/ewallet_db/exchange_pair.ex

Issue/Task Number: T450
Add Admin API endpoints to allow getting/creating/updating/deleting exchange pairs.
- Updated `EWallet.UUIDFetcher` to support `from_token_id` and `to_token_id`
- Add a serializer, a view, a policy, a controller and their tests to support `/exchange_pair.*` endpoints
- Updated Admin API's specs
This is straightforward CRUD endpoints.
**/exchange_pair.all:**
```sh
curl -X POST \
10.5.10.10:4000/api/admin/exchange_pair.all \
-H 'accept: application/vnd.omisego.v1+json' \
-H "Authorization: OMGAdmin $(echo -n "you_user_id:your_auth_token" | base64 | tr -d '\n')" \
-v -w "\n" | jq
```
**/exchange_pair.get:**
```sh
curl -X POST \
10.5.10.10:4000/api/admin/exchange_pair.get \
-H 'accept: application/vnd.omisego.v1+json' \
-H …
```

Add /exchange_pair.* endpoints

---

apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
apps/admin_api/lib/admin_api/v1/router.ex
apps/admin_api/priv/spec.yaml
apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/provider_auth/token_controller_test.exs
apps/ewallet_db/lib/ewallet_db/token.ex
apps/ewallet_db/test/ewallet_db/token_test.exs

Issue/Task Number: T287
This PR adds the new `token.update` endpoint, usable by admins and providers.
- All necessary stuff to make it work :)

Add token.update endpoint

---

apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs

This PR adds the requester's channels to the list of channels notified when a consumption is finalized.

Notify requester when consumption is finalized

---

apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
apps/admin_api/lib/admin_api/v1/controllers/user_controller.ex
apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
apps/admin_api/lib/admin_api/v1/router.ex
apps/admin_api/priv/spec.yaml
apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
apps/admin_panel/assets/src/omg-users/action.js
apps/admin_panel/assets/src/services/userService.js
apps/ewallet/lib/ewallet/policies/transaction_policy.ex
apps/ewallet/lib/ewallet/policies/user_policy.ex
apps/ewallet_db/lib/ewallet_db/account.ex
apps/ewallet_db/lib/ewallet_db/transaction.ex
apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
apps/ewallet_db/lib/ewallet_db/transaction_request.ex
apps/ewallet_db/lib/ewallet_db/wallet.ex

Issue/Task Number: T499
This PR adds all `/account.get_xxx` endpoints allowing the retrieval of more specific data related to accounts.

Fix all account.get_ endpoints

---

apps/ewallet_db/priv/repo/reporters/seeds.exs
apps/ewallet_db/priv/repo/reporters/seeds_sample.exs
apps/ewallet_db/priv/repo/seeds/02_key.exs
apps/ewallet_db/priv/repo/seeds_sample/01_auth_token.exs

This PR attempts to update & improve the output for `mix seed` and `mix seed --sample`.
- Updated the seed outputs of `mix seed` and `mix seed --sample`
- Added a Key seed
I shortened a lot of wordy text as I realized the shell is not the best place to read something long 🤦‍♂️. Plus a lot of the information is redundant with the readme. 
Since we now have the Admin Panel and a clearer separation between Admin API and eWallet API, I've also removed those parts that in `mix seed` output.
Run `mix seed` and `mix seed --sample` to see the new outputs.
**Example:**
(I'm leaving all the credentials in on purpose, they were generated and wiped on my local machine)
```
Setting up the OmiseGO eWallet Server
We have seeded the minimum amount of data for you to start a …
```

Update `mix seed` and `mix seed --sample` output

---

apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex

Issue/Task Number: T506
This PR prevents the consumption event from being sent two times in the eWallet API. This should also fix the consumption event being sent when getting a consumption in the Admin API.

Handle consumption events properly

---

apps/ewallet/lib/ewallet/policies/transaction_consumption_policy.ex
apps/ewallet/lib/ewallet/policies/transaction_policy.ex
apps/ewallet/lib/ewallet/policies/transaction_request_policy.ex
apps/ewallet/lib/ewallet/policies/wallet_policy.ex
apps/ewallet/lib/ewallet/web/v1/error_handler.ex

Issue/Task Number: T507
This PR fixes some permission issues we just discovered with the transaction creation and transaction request retrieval.

Fix permissions for transaction and requests

---

apps/admin_api/priv/spec.yaml

Fix the body shown in OpenAPI spec for `/account.get_wallets`.

Update Swagger for /account.get_wallets

---

apps/admin_panel/assets/src/omg-transaction/action.js
apps/admin_panel/assets/src/omg-transaction/action.test.js
apps/admin_panel/assets/src/omg-transaction/reducer.js
apps/admin_panel/assets/src/omg-transaction/reducer.test.js
apps/admin_panel/assets/src/omg-transaction/selector.js
apps/admin_panel/assets/src/omg-transaction/transactionsFetcher.js
apps/admin_panel/assets/src/services/transactionService.js

Add test cases for transactions enitity
- Add action test
- Add reducer test

Add transaction test

---

apps/admin_panel/assets/src/omg-mint-token-modal/index.js
apps/admin_panel/assets/src/omg-token/action.js
apps/admin_panel/assets/src/omg-token/action.test.js
apps/admin_panel/assets/src/omg-token/reducer.js
apps/admin_panel/assets/src/omg-token/reducer.test.js
apps/admin_panel/assets/src/services/tokenService.js

Add test cases for token enitity
- Add action test
- Add reducer test

Add Token test

---

apps/admin_panel/assets/src/omg-users/userProvider.js
apps/admin_panel/assets/src/omg-wallet/action.js
apps/admin_panel/assets/src/omg-wallet/action.test.js
apps/admin_panel/assets/src/omg-wallet/reducer.js
apps/admin_panel/assets/src/omg-wallet/reducer.test.js
apps/admin_panel/assets/src/omg-wallet/selector.js
apps/admin_panel/assets/src/omg-wallet/selector.test.js
apps/admin_panel/assets/src/services/walletService.js

Add test cases for wallet enitity
- Add action test
- Add reducer test
- Add selector test

Add Wallet test

---

apps/admin_panel/assets/src/omg-access-key/action.js
apps/admin_panel/assets/src/omg-access-key/action.test.js
apps/admin_panel/assets/src/omg-access-key/reducer.js
apps/admin_panel/assets/src/omg-access-key/reducer.test.js
apps/admin_panel/assets/src/omg-api-keys/action.js
apps/admin_panel/assets/src/omg-api-keys/action.test.js
apps/admin_panel/assets/src/omg-api-keys/reducer.js
apps/admin_panel/assets/src/omg-api-keys/reducer.test.js
apps/admin_panel/assets/src/omg-cache/reducer.js
apps/admin_panel/assets/src/omg-page-api/index.js
apps/admin_panel/assets/src/reducer/index.js
apps/admin_panel/assets/src/services/accessKeyService.js

Add test for api key and access key.
- Add test for api key action.
- Add test for api key reducer.
- Add test for access key action.
- Add test for access key reducer.
- Renaming.
- Fix minor typo bugs.
deploy as usual

Add Access key test / Api key test

---

apps/admin_panel/assets/src/omg-consumption/action.js
apps/admin_panel/assets/src/omg-consumption/action.test.js
apps/admin_panel/assets/src/omg-consumption/reducer.js
apps/admin_panel/assets/src/omg-consumption/reducer.test.js
apps/admin_panel/assets/src/omg-transaction-request/action.js
apps/admin_panel/assets/src/omg-transaction-request/action.test.js
apps/admin_panel/assets/src/omg-transaction-request/reducer.js
apps/admin_panel/assets/src/omg-transaction-request/reducer.test.js

Add test for transaction request.
- Add test for transaction request action.
- Add test for transaction request reducer.
- Add test for consumptions action.
- Add test for consumptions reducer.
- Refactor
deploy as usual

Add transaction request/consumption test

---

apps/admin_panel/assets/src/omg-invite/action.js
apps/admin_panel/assets/src/omg-user-current/action.js
apps/admin_panel/assets/src/omg-user-current/action.test.js
apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
apps/admin_panel/assets/src/omg-user-current/reducer.js
apps/admin_panel/assets/src/omg-users/action.js
apps/admin_panel/assets/src/omg-users/action.test.js
apps/admin_panel/assets/src/omg-users/reducer.js
apps/admin_panel/assets/src/omg-users/reducer.test.js
apps/admin_panel/assets/src/services/userService.js

Add test for users and current user.
- Add test for users and current user action.
- Add test for users and current reducer.
- Renaming.
- Fix minor typo bugs.
deploy as usual

Add user test

---

apps/admin_panel/assets/src/omg-uikit/avatar/index.js
apps/admin_panel/assets/src/omg-wallet-select/index.js
apps/admin_panel/assets/src/socket/connector.js

Closes #427 
This PR handle edge case when the name is undefined/null .
- Handle case for undefined avatar

Handle edge case for avatar component

---

README.md
docs/setup/bare_metal.md
docs/setup/docker.md
docs/setup/troubleshooting.md
docs/setup/vagrant.md

Closes #435.
This PR adds a troubleshooting guide to the documentations.
- Added `docs/setup/troubleshooting.md`
N/A
N/A
N/A

Add common troubleshooting guide

---

apps/admin_api/lib/admin_api/application.ex
apps/ewallet/lib/ewallet/web/config.ex
apps/ewallet_api/lib/ewallet_api/application.ex
apps/ewallet_api/lib/ewallet_api/endpoint.ex

Closes #448
This PR adds CORSPlug to the ClientAPI's router so that CORS is properly handled/supported.
- Refactor `AdminAPI.Config` to `EWallet.Web.Config`
- Add `CORSPlug` to `EWalletAPI.Application`
-
Make any requests from a javascript browser app. CORS should be supported.
No changes to the API or DB.

Apply CORSPlug to both AdminAPI and ClientAPI

---

apps/ewallet/lib/ewallet/web/filters/match_all_parser.ex
apps/ewallet/lib/ewallet/web/filters/match_any_parser.ex
apps/ewallet/lib/ewallet/web/filters/match_parser.ex
apps/ewallet/lib/ewallet/web/orchestrator.ex
apps/ewallet/test/ewallet/web/filters/match_all_parser_test.exs

Issue/Task Number: #484
closes #484
This PR adds support for the mapped fields to the `MatchParser`.

Handle mappings in MatchParser

---

apps/admin_api/test/admin_api/v1/controllers/admin_auth/configuration_controller_test.exs
apps/ewallet_config/lib/ewallet_config/setting.ex
apps/ewallet_config/lib/ewallet_config/setting_validator.ex

Issue/Task Number: #576
#576
This PR fixes the update setting flow which was broken with encrypted values.

Handle value casting for update properly

---

README.md

Issue/Task Number: #591 
Closes #591
Adds a reference to the Point of Sale apps to the main readme
- Updated readme
N/A
N/A
No changes to API docs or DB schemas

Add references to the Point of Sale apps in the readme

---

apps/admin_panel/assets/src/socket/connector.js
apps/admin_panel/assets/src/socket/connector.test.js

Fix test case for url

---

apps/admin_panel/assets/src/services/userService.js

Endpoint name for getting users is wrong, this PR fixes it.

Fix endpoint name for user endpoint

---

.circleci/config.yml

I thought about using [Slack Orb](
https://circleci.com/orbs/registry/orb/circleci/slack) but it doesn’t output what I like, so here you are, `curl` inside build steps. Also this PR upgrade `circle.yml` to version `2.1` to enjoy some extra functionalities such as reusable commands and executors. 
I have this pet theory that all configuration format will eventually become Lisp. The clock sure is ticking.

Improve Slack notifications

---

apps/admin_panel/assets/src/omg-account-current/currentAccountProvider.js
apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
apps/admin_panel/assets/src/omg-login-form/index.js
apps/admin_panel/assets/src/omg-page-account-setting/index.js
apps/admin_panel/assets/src/omg-page-account/index.js
apps/admin_panel/assets/src/omg-page-activity-log/index.js
apps/admin_panel/assets/src/omg-page-configuration/index.js
apps/admin_panel/assets/src/omg-page-token/index.js
apps/admin_panel/assets/src/omg-page-transaction/index.js
apps/admin_panel/assets/src/omg-uikit/table/index.js
apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js

Fix wording in the application.
- Fix typo and grammar.
- Fix bouncing table loading style.

Minor Improve content grammar and bug fixes

---

apps/admin_panel/assets/src/index.js
apps/admin_panel/assets/src/omg-consumption-panel/index.js
apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
apps/admin_panel/assets/src/omg-page-account-detail/index.js
apps/admin_panel/assets/src/omg-page-account-setting/index.js
apps/admin_panel/assets/src/omg-page-account/index.js
apps/admin_panel/assets/src/omg-page-activity-log/ActivityPanel.js
apps/admin_panel/assets/src/omg-page-activity-log/index.js
apps/admin_panel/assets/src/omg-page-api/index.js
apps/admin_panel/assets/src/omg-page-configuration/index.js
apps/admin_panel/assets/src/omg-page-consumption/index.js
apps/admin_panel/assets/src/omg-page-dashboard/index.js
apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
apps/admin_panel/assets/src/omg-page-token-detail/HistoryTable.js
apps/admin_panel/assets/src/omg-page-token-detail/index.js
apps/admin_panel/assets/src/omg-page-token/index.js
apps/admin_panel/assets/src/omg-page-transaction-export/index.js
apps/admin_panel/assets/src/omg-page-transaction-request/index.js
apps/admin_panel/assets/src/omg-page-transaction/index.js
apps/admin_panel/assets/src/omg-page-user-detail/index.js
apps/admin_panel/assets/src/omg-page-users/index.js
apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
apps/admin_panel/assets/src/omg-page-wallets/index.js
apps/admin_panel/assets/src/omg-transaction-panel/index.js
apps/admin_panel/assets/src/omg-transaction-request-tab/ActivityList.js
apps/admin_panel/assets/src/omg-transaction-request-tab/TransactionRequestDetail.js
apps/admin_panel/assets/src/services/configurationService.js

Issue/Task Number: - 
Since we've decided a format for datetime, so it's time to refactor. This PR also include bug fix for transaction request.
- Fix create transaction request bug, so you can create with default account id now.
- Refactor datetime format everywhere.
- Date format should be the same everywhere.
- Try creating transaction request with default value.

Fix format timezone and transaction request create bug

---

apps/admin_panel/assets/src/omg-page-configuration/index.js

Fix aws name typo.
- Fix aws name typo.
Go to config page, switch to aws; should show the correct name.

Fix aws name typo

---

apps/activity_logger/mix.exs
apps/admin_api/mix.exs
apps/admin_panel/mix.exs
apps/ewallet/config/config.exs
apps/ewallet/mix.exs
apps/ewallet_api/mix.exs
apps/ewallet_config/mix.exs
apps/ewallet_db/mix.exs
apps/load_tester/mix.exs
apps/local_ledger/mix.exs
apps/local_ledger_db/mix.exs
apps/url_dispatcher/mix.exs
apps/utils/mix.exs

Blocked by #777
All relevant tasks in milestone v1.1 are cleared. Ready for another pre-release. Hopefully the final one.
- Updated version in all `Mixfile`
N/A
N/A
N/A

Release v1.1.0-pre.3

---

apps/activity_logger/mix.exs
apps/admin_api/mix.exs
apps/admin_panel/mix.exs
apps/ewallet/config/config.exs
apps/ewallet/mix.exs
apps/ewallet_api/mix.exs
apps/ewallet_config/mix.exs
apps/ewallet_db/mix.exs
apps/load_tester/mix.exs
apps/local_ledger/mix.exs
apps/local_ledger_db/mix.exs
apps/url_dispatcher/mix.exs
apps/utils/mix.exs
docker-gen.sh

This PR prepares the codebase for `v.1.1.0` stable.
- Update Mixfile and docker-related files to `v1.1.0`
N/A
N/A
N/A

Version bump 1.1.0

---

.circleci/config.yml
Makefile

Closes #751 
Setup automatic deploy from master branch to staging.
CircleCI configuration changes.

Deploy master branch to staging

---

.circleci/ci_deploy.sh
.circleci/ci_e2e.sh
.circleci/ci_publish.sh
.circleci/config.yml
Makefile

* Remove Circle CI cache as it’s causing NIF to fail to load.
* Simplify `.circleci/config.yml` by using short form for `run:`
* Simplify `.circleci/config.yml` by splitting long scripts into an actual script file.
* Use `make docker` in CI so we have consistent way to build Docker image.
* Improve conditional CI steps using ENV var detection instead of `CIRCLE_PROJECT_USERNAME`.

Fix production image compilation 

---

.circleci/ci_publish.sh
.circleci/config.yml

Fix staging deploy due to missing `checkout` step.

Fix staging deploy

---

.circleci/ci_deploy.sh
.circleci/ci_e2e.sh
.circleci/ci_publish.sh
.circleci/config.yml
Makefile

Sync CI changes to v1.2

---

apps/admin_api/priv/spec.json
apps/admin_api/priv/spec.yaml
apps/admin_api/priv/swagger/api_key/paths.yaml
apps/admin_api/priv/swagger/api_key/request_bodies.yaml
apps/admin_api/priv/swagger/api_key/response_schemas.yaml
apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
apps/admin_api/test/admin_api/v1/views/api_key_view_test.exs
apps/ewallet/lib/ewallet/web/v1/serializers/api_key_serializer.ex
apps/ewallet/test/ewallet/web/v1/serializers/api_key_serializer_test.exs
apps/ewallet_db/lib/ewallet_db/api_key.ex
apps/ewallet_db/priv/repo/migrations/20190312075544_add_name_to_api_keys.exs
apps/ewallet_db/test/ewallet_db/api_key_test.exs
apps/ewallet_db/test/support/factory.ex

Issue/Task Number: #845 
Closes #845
Add name to API Keys.

Add name to API Keys

---

Makefile
apps/status/config/config.exs
apps/status/config/test.exs
apps/status/lib/status.ex
apps/utils/lib/helpers/path_resolver.ex
docker-compose.yml

fix: env variables

---

apps/admin_api/lib/admin_api/v1/controllers/permission_controller.ex
apps/admin_api/lib/admin_api/v1/router.ex
apps/admin_api/lib/admin_api/v1/views/permission_view.ex
apps/admin_api/priv/spec.json
apps/admin_api/priv/spec.yaml
apps/admin_api/priv/swagger/permission/paths.yaml
apps/admin_api/priv/swagger/permission/response_schemas.yaml
apps/admin_api/priv/swagger/permission/responses.yaml
apps/admin_api/priv/swagger/permission/schemas.yaml
apps/admin_api/priv/swagger/swagger.yaml
apps/admin_api/test/admin_api/v1/controllers/permission_controller_test.exs
apps/admin_api/test/admin_api/v1/views/permission_view_test.exs
apps/ewallet/lib/ewallet/permissions/bouncer/dispatch_config.ex
apps/ewallet/lib/ewallet/permissions/bouncer/targets/global_role_target.ex
apps/ewallet/lib/ewallet/permissions/bouncer/targets/role_target.ex
apps/ewallet/lib/ewallet/policies/global_role_policy.ex
apps/ewallet/lib/ewallet/policies/role_policy.ex
apps/ewallet/lib/ewallet/web/v1/serializers/permission_serializer.ex
apps/ewallet/test/ewallet/web/v1/serializers/permission_serializer_test.exs
apps/ewallet_db/lib/ewallet_db/global_role.ex
apps/ewallet_db/lib/ewallet_db/role.ex

Issue/Task Number: #835
Closes #835
Add a new `/api/admin/permission.all` endpoint that list all role-permission mappings in the system.
- Add `/api/admin/permission.all` and its related controllers, views, serializers, OpenAPI specs, etc.
- Add `EWallet.Bouncer.GlobalRoleTarget`, `EWallet.Bouncer.RoleTarget`, `EWallet.GlobalRolePolicy`, `EWallet.RolePolicy` to support permissioning
- Add `/api/admin/permission.all` to OpenAPI specs
Basically the controller takes the permissions specified in `GlobalRole.global_role_permissions()` and `Role.account_role_permissions()` and map it into a response with `global_roles: ...` and `account_roles: ...` respectively.
```shell
curl localhost:4000/api/admin/permission.all \
-H "Authorization: OMGAdmin …
```

Add /permission.all

---

.circleci/ci_deploy.sh
.circleci/config.yml

Fix CI deploy due to recent changes in deploy repository.

Fix CI deploy

---

apps/blockchain_eth/lib/blockchain_eth/worker.ex
apps/blockchain_eth/mix.exs
apps/blockchain_eth/test/blockchain_eth/worker_test.exs
apps/blockchain_eth/test/test_helper.exs
apps/ewallet/lib/ewallet/release_tasks/init_db.ex
apps/keychain/.formatter.exs
apps/keychain/.gitignore
apps/keychain/README.md
apps/keychain/config/config.exs
apps/keychain/config/dev.exs
apps/keychain/config/prod.exs
apps/keychain/config/test.exs
apps/keychain/lib/keychain.ex
apps/keychain/lib/keychain/application.ex
apps/keychain/lib/keychain/key.ex
apps/keychain/lib/keychain/repo.ex
apps/keychain/lib/keychain/types/binary.ex
apps/keychain/lib/keychain/vault.ex
apps/keychain/mix.exs
apps/keychain/priv/repo/migrations/20190314162613_add_keychain_table.exs
apps/keychain/test/keychain/key_test.exs
apps/keychain/test/keychain_test.exs
apps/keychain/test/support/factory.ex
apps/keychain/test/test_helper.exs

Persist generated private key in Keychain DB

---

docs/setup/upgrading/README.md
docs/setup/upgrading/v1.2.0.md

Issue/Task Number: #821 
closes #821 
This PR adds the upgrading doc for 1.2.0.

Upgrade Doc for 1.2.0

---

apps/admin_panel/assets/src/omg-access-key/searchField.js
apps/admin_panel/assets/src/omg-admins/searchField.js
apps/admin_panel/assets/src/omg-page-admins/index.js
apps/admin_panel/assets/src/omg-page-api/AdminKeySection.js
apps/admin_panel/assets/src/omg-page-each-account/AccountAdminSubPage.js
apps/admin_panel/assets/src/omg-page-each-account/AccountKeySubPage.js
apps/admin_panel/assets/src/omg-page-each-account/AccountNavigationBar.js
apps/admin_panel/assets/src/services/accountService.js

Issue/Task Number: [922](https://github.com/omisego/ewallet/issues/922)
use new endpoints when fetching account keys/admins
- account.get_key_memberships
- account.get_admin_user_memberships
Check all fields in account keys/admins tables are correct

New membership endpoints

---

apps/admin_panel/assets/src/omg-cache/reducer.js
apps/admin_panel/assets/src/omg-member/reducer.js
apps/admin_panel/assets/src/omg-member/reducer.test.js
apps/admin_panel/assets/src/omg-page-each-account/AccountLayout.js
apps/admin_panel/assets/src/omg-page-transaction/index.js
apps/admin_panel/assets/src/omg-uikit/breadcrumb/index.js

Issue/Task Number: - 
Minor UI and redux store bug fixes.
- Fix member invite redux store bug.
- Remove divider from account scope

Minor bug fix

---

apps/frontend/assets/src/omg-page-activity-log/index.js

Issue/Task Number: - 
The UI for activity log is broken due to I forget to remove display flex;
- Fix display for activity page.

fix flex bug

---

apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
apps/ewallet/lib/ewallet/web/v1/error_handler.ex
apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs

Issue/Task Number: #1002 
Closes #1002 
This PR allows end users to consume a transaction request if the exchange pair allows it.

Allow consumption with different token for client if exchange pair ok

---

apps/frontend/assets/src/adminPanelApp/action.js
apps/frontend/assets/src/adminPanelApp/index.js
apps/frontend/assets/src/adminPanelApp/routes/authenticatedRoute.js
apps/frontend/assets/src/adminPanelApp/routes/index.js
apps/frontend/assets/src/index.js
apps/frontend/assets/src/omg-login-form/index.js
apps/frontend/assets/src/omg-session/reducer.js
apps/frontend/assets/src/omg-session/selector.js
apps/frontend/assets/src/omg-user-current/action.test.js
apps/frontend/assets/src/reducer/index.js
apps/frontend/assets/src/socket/connector.js
apps/frontend/assets/src/socket/connector.test.js

Issue/Task Number: #959 
There is another bug when logging it with invalid token, this bug happen when you are in another page and token is not valid => get redirect to login => login correctly and it freeze because authentication state didn't get updated.
- Fix websocket calling when not connected.
- Fix authentication state.
- Minor refactoring.
Login to random page on admin, clear cache and you should get redirect back to login => login and you should get back to the same page.

959 fix login

---

apps/frontend/assets/src/omg-create-transaction-request-modal/index.js
apps/frontend/assets/src/utils/formatter.js
apps/frontend/assets/src/utils/formatter.test.js

Issue/Task Number: #1020 
The formatter is missing edge case and return `nan` value because we cast string before checking.
- Fix formatter test.
- Add missing state
Create transaction request should work correctly.

Fix transaction request modal bug

---

apps/frontend/assets/src/omg-access-key/reducer.js
apps/frontend/assets/src/omg-admins/action.js
apps/frontend/assets/src/omg-admins/reducer.js
apps/frontend/assets/src/omg-alert/reducer.js
apps/frontend/assets/src/omg-api-keys/reducer.js
apps/frontend/assets/src/omg-member/reducer.js
apps/frontend/assets/src/omg-page-admin-detail/index.js
apps/frontend/assets/src/omg-page-user-detail/index.js
apps/frontend/assets/src/omg-token/reducer.js
apps/frontend/assets/src/omg-users/action.js
apps/frontend/assets/src/omg-users/reducer.js
apps/frontend/assets/src/omg-wallet/reducer.js
apps/frontend/assets/src/services/adminService.js
apps/frontend/assets/src/services/userService.js

Issue/Task Number: #1024 
Add update user/ admin function.
- Add update user.
- Add update admin.
- Remove some legacy code.
Due to we have many new components on 1.3, this is just a fast way to do it. Will refactor later.
Go to user, admin and click edit to change data.

Update user and admin

---

Makefile
apps/ewallet/lib/mix/tasks/omg.deps.ex
apps/frontend/assets/README.md
apps/frontend/lib/frontend/application.ex
docs/setup/bare_metal.md
docs/setup/macos/brew_install_dependencies.md
docs/setup/upgrading/README.md

Remove yarn installation and use default npm.
- Remove yarn installation and use default npm.
-
-
Not sure, need @sirn to comfirm

Remove yarn

---

apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
apps/ewallet_db/lib/ewallet_db/transaction_request.ex

Issue/Task Number: #1074 
Closes #1074 
This PR removes duplicate function in `transaction_request.ex` and unused variable.

Cleanup warning

---

apps/frontend/assets/src/adminPanelApp/index.js
apps/frontend/assets/src/adminPanelApp/routes/index.js
apps/frontend/assets/src/omg-alert/reducer.js
apps/frontend/assets/src/omg-consumption-panel/ConsumptionBox.js
apps/frontend/assets/src/omg-consumption-panel/index.js
apps/frontend/assets/src/omg-consumption/action.js
apps/frontend/assets/src/omg-consumption/reducer.js
apps/frontend/assets/src/omg-page-consumption/index.js
apps/frontend/assets/src/omg-page-transaction/TransactionTable.js
apps/frontend/assets/src/omg-page-transaction/index.js
apps/frontend/assets/src/omg-transaction-request-tab/ConsumeBox.js
apps/frontend/assets/src/omg-transaction-request-tab/PropertiesTab.js
apps/frontend/assets/src/omg-transaction-request/action.js
apps/frontend/assets/src/omg-transaction-request/reducer.js
apps/frontend/assets/src/services/consumptionService.js
apps/frontend/assets/src/services/transactionRequestService.js

Issue/Task Number: #1017 
Add the ability to remove cancel transaction request / consumption
- Refactor the transaction request
- Cancel transaction request
- Cancel comsumption
Try creating transaction request, cancel it in the panel, also consumption.

Cancel transaction request consumption

---

README.md

Issue/Task Number: 974
Replace waffles badge with Shields.io Issues badge in project README

Replace waffles badge with Shields.io Issues badge [closes 974]

---

apps/frontend/assets/src/omg-createNewPassword-form/index.js

Issue/Task Number: #1103 
We updated the action creator but forget to update the form, this PR fixes it.
- Fix error code.

Fix reset password bug

---

apps/frontend/assets/src/adminPanelApp/routes/index.js
apps/frontend/assets/src/omg-alert/reducer.js
apps/frontend/assets/src/omg-createNewPassword-form/index.js
apps/frontend/assets/src/omg-session/reducer.js

Issue/Task Number: #1103 
- Fix error forget password
- Fix error not showing when invite failed

Fix forget password / alert invite admin

---

apps/frontend/assets/src/omg-create-transaction-modal/index.js
apps/frontend/assets/src/omg-token-select/index.js
apps/frontend/assets/src/omg-uikit/index.js
apps/frontend/assets/src/omg-uikit/input/index.js
apps/frontend/assets/src/omg-uikit/select/index.js
apps/frontend/assets/src/omg-uikit/selectInput/index.js

issue #1102
ui component for new design. wrapper over select & input.
Implemented it for global transfer modal. 
https://gallery.io/projects/MCHbtQVoQ2HCZfyN0ITInFtb/files/MCEJu8Y2hyDScUKnMG1qETPXk0_H_OMFTOk

new select wrapper

---

apps/frontend/assets/src/adminPanelApp/routes/index.js
apps/frontend/assets/src/adminPanelApp/theme.js
apps/frontend/assets/src/omg-alert/index.js
apps/frontend/assets/src/omg-alert/reducer.js
apps/frontend/assets/src/omg-app-layout/SideNavigation.js
apps/frontend/assets/src/omg-page-configuration/BlockchainSettings.js
apps/frontend/assets/src/omg-page-configuration/CacheSettings.js
apps/frontend/assets/src/omg-page-configuration/ConfigRow.js
apps/frontend/assets/src/omg-page-configuration/EmailSettings.js
apps/frontend/assets/src/omg-page-configuration/FileStorageSettings.js
apps/frontend/assets/src/omg-page-configuration/GlobalSettings.js
apps/frontend/assets/src/omg-page-configuration/index.js

Issue/Task Number: https://github.com/omisego/ewallet/issues/1119
https://gallery.io/projects/MCHbtQVoQ2HCZfyN0ITInFtb/files/MCEJu8Y2hyDScSavJ4fVcnij3YETz93IPwQ
Moved each configuration setting to separate pages
Blockchain settings is just placeholder for now, not hooked up yet, also blockchain connection status is dummy placeholder for now

Blockchain configuration page ui

---

README.md
apps/ewallet_config/config/config.exs
apps/load_tester/mix.exs
docs/setup/README.md
docs/setup/advanced/env.md
docs/setup/advanced/settings.md
docs/tests/README.md

Documentation fixes per @cduangprom 's request for a technical review.
- Fix load testing and seed commands
- Consolidate upgrade links
- Add the missing `seed --settings` to seed section
- Fix link from Setup back to main readme
- Add missing settings to Settings page
- Small formatting adjustments
- The upgrade from v1.0 link is removed since it's outdated now
N/A
All textual fixes.

Documentation fixes

---

apps/ewallet_config/config/config.exs

This fixes #1146 issue that's causing a formatting error.
- Ran `mix format` again
N/A
N/A
Code formatting only

Fix formatting error
